// DCA Agencies seed data - first 10 agencies
module.exports = [
  {
    dca_id: 'DCA-CUSTIND-01',
    agency_name: 'Customs Recovery Specialists India Pvt Ltd',
    short_name: 'Customs Recovery India',
    specialization: 'CUSTOMS_DISPUTE',
    regions: 'South_India,North_India',
    contact_person: 'Ravi Kumar',
    contact_phone: '+91-9845012345',
    contact_email: 'ravi@customsrecovery.in',
    recovery_rate_overall: 0.78,
    avg_days_to_recovery: 28,
    total_cases_handled: 2456,
    commission_rate: 0.28,
    min_case_amount: 5000,
    max_case_amount: 500000,
    status: 'ACTIVE',
    performance_score: 8.4,
    sla_first_contact_hours: 24,
    sla_recovery_days: 45,
    created_date: '2025-01-15',
    last_performance_review: '2026-01-07',
    api_endpoint: 'https://dca-customsindia.com/api',
    api_auth_token: 'fedex_dca_token_01',
    is_preferred_partner: 1,
    notes: 'Excellent on customs disputes',
  },
  {
    dca_id: 'DCA-FRTGEN-02',
    agency_name: 'Freight Collections Nationwide',
    short_name: 'Freight Col',
    specialization: 'FREIGHT_GENERAL',
    regions: 'All India',
    contact_person: 'Anita Desai',
    contact_phone: '+91-9845012346',
    contact_email: 'anita@freightcol.in',
    recovery_rate_overall: 0.82,
    avg_days_to_recovery: 22,
    total_cases_handled: 5100,
    commission_rate: 0.25,
    min_case_amount: 2000,
    max_case_amount: 100000,
    status: 'ACTIVE',
    performance_score: 8.8,
    sla_first_contact_hours: 24,
    sla_recovery_days: 40,
    created_date: '2025-01-20',
    last_performance_review: '2026-01-05',
    api_endpoint: 'https://api.freightcol.in/v1',
    api_auth_token: 'fedex_dca_token_02',
    is_preferred_partner: 1,
    notes: 'Best for general freight',
  },
  {
    dca_id: 'DCA-B2BEXP-05',
    agency_name: 'B2B Collections Experts',
    short_name: 'B2B Experts',
    specialization: 'B2B_CASHFLOW',
    regions: 'Industrial Hubs',
    contact_person: 'Vikram Malhotra',
    contact_phone: '+91-9845012349',
    contact_email: 'vikram@b2bexperts.com',
    recovery_rate_overall: 0.85,
    avg_days_to_recovery: 25,
    total_cases_handled: 3200,
    commission_rate: 0.26,
    min_case_amount: 15000,
    max_case_amount: 1000000,
    status: 'ACTIVE',
    performance_score: 9.1,
    sla_first_contact_hours: 12,
    sla_recovery_days: 45,
    created_date: '2025-03-01',
    last_performance_review: '2026-01-07',
    api_endpoint: 'https://b2bexperts.com/api',
    api_auth_token: 'fedex_dca_token_05',
    is_preferred_partner: 1,
    notes: 'Top performer B2B',
  },
  {
    dca_id: 'DCA-LEGAL-04',
    agency_name: 'Legal Debt Recovery Partners',
    short_name: 'LDR Partners',
    specialization: 'HIGH_COMPLEXITY',
    regions: 'All India',
    contact_person: 'Sanjay Gupta',
    contact_phone: '+91-9845012348',
    contact_email: 'legal@ldrpartners.in',
    recovery_rate_overall: 0.68,
    avg_days_to_recovery: 45,
    total_cases_handled: 850,
    commission_rate: 0.35,
    min_case_amount: 100000,
    max_case_amount: 5000000,
    status: 'ACTIVE',
    performance_score: 7.5,
    sla_first_contact_hours: 24,
    sla_recovery_days: 60,
    created_date: '2025-01-10',
    last_performance_review: '2026-01-06',
    api_endpoint: 'https://api.ldrpartners.in',
    api_auth_token: 'fedex_dca_token_04',
    is_preferred_partner: 1,
    notes: 'Use for litigation cases',
  },
  {
    dca_id: 'DCA-FIELD-08',
    agency_name: 'Field Collection Specialists',
    short_name: 'Field Specs',
    specialization: 'UNREACHABLE',
    regions: 'Tier2 Cities',
    contact_person: 'Amit Verma',
    contact_phone: '+91-9845012352',
    contact_email: 'amit@fieldspecs.in',
    recovery_rate_overall: 0.71,
    avg_days_to_recovery: 38,
    total_cases_handled: 950,
    commission_rate: 0.32,
    min_case_amount: 5000,
    max_case_amount: 200000,
    status: 'ACTIVE',
    performance_score: 7.8,
    sla_first_contact_hours: 48,
    sla_recovery_days: 55,
    created_date: '2025-02-28',
    last_performance_review: '2026-01-07',
    api_endpoint: 'https://fieldspecs.in/api',
    api_auth_token: 'fedex_dca_token_08',
    is_preferred_partner: 0,
    notes: 'Good for physical visits',
  },
  {
    dca_id: 'DCA-ENTERP-10',
    agency_name: 'Enterprise Debt Solutions',
    short_name: 'Ent Solutions',
    specialization: 'HIGH_VALUE_B2B',
    regions: 'Metro Cities',
    contact_person: 'Robert D',
    contact_phone: '+91-9845012354',
    contact_email: 'robert@entsol.com',
    recovery_rate_overall: 0.79,
    avg_days_to_recovery: 33,
    total_cases_handled: 1100,
    commission_rate: 0.29,
    min_case_amount: 500000,
    max_case_amount: 10000000,
    status: 'ACTIVE',
    performance_score: 8.5,
    sla_first_contact_hours: 12,
    sla_recovery_days: 60,
    created_date: '2025-03-15',
    last_performance_review: '2026-01-06',
    api_endpoint: 'https://entsol.com/api',
    api_auth_token: 'fedex_dca_token_10',
    is_preferred_partner: 1,
    notes: 'Strategic partner',
  },
  {
    dca_id: 'DCA-NORTH-11',
    agency_name: 'Northern Territories Recovery',
    short_name: 'North Rec',
    specialization: 'CUSTOMS_DISPUTE',
    regions: 'North_India',
    contact_person: 'Manish T',
    contact_phone: '+91-9845012355',
    contact_email: 'manish@northrec.in',
    recovery_rate_overall: 0.74,
    avg_days_to_recovery: 30,
    total_cases_handled: 1800,
    commission_rate: 0.28,
    min_case_amount: 5000,
    max_case_amount: 300000,
    status: 'ACTIVE',
    performance_score: 7.9,
    sla_first_contact_hours: 24,
    sla_recovery_days: 45,
    created_date: '2025-06-01',
    last_performance_review: '2026-01-02',
    api_endpoint: 'https://northrec.in/api',
    api_auth_token: 'token_11',
    is_preferred_partner: 0,
    notes: '',
  },
  {
    dca_id: 'DCA-EAST-13',
    agency_name: 'Eastern Freight Solutions',
    short_name: 'East Sol',
    specialization: 'FREIGHT_GENERAL',
    regions: 'East_India',
    contact_person: 'Rahul M',
    contact_phone: '+91-9845012357',
    contact_email: 'rahul@eastsol.in',
    recovery_rate_overall: 0.69,
    avg_days_to_recovery: 32,
    total_cases_handled: 1100,
    commission_rate: 0.26,
    min_case_amount: 2000,
    max_case_amount: 100000,
    status: 'WARNING',
    performance_score: 6.8,
    sla_first_contact_hours: 36,
    sla_recovery_days: 45,
    created_date: '2025-06-15',
    last_performance_review: '2026-01-01',
    api_endpoint: 'https://eastsol.in/api',
    api_auth_token: 'token_13',
    is_preferred_partner: 0,
    notes: 'Slow response times',
  },
  {
    dca_id: 'DCA-GLOBAL-18',
    agency_name: 'Global Trade Recovery',
    short_name: 'Global Rec',
    specialization: 'CUSTOMS_DISPUTE',
    regions: 'All India',
    contact_person: 'John D',
    contact_phone: '+91-9845012362',
    contact_email: 'john@globalrec.com',
    recovery_rate_overall: 0.8,
    avg_days_to_recovery: 27,
    total_cases_handled: 3100,
    commission_rate: 0.29,
    min_case_amount: 10000,
    max_case_amount: 750000,
    status: 'ACTIVE',
    performance_score: 8.7,
    sla_first_contact_hours: 24,
    sla_recovery_days: 40,
    created_date: '2025-01-25',
    last_performance_review: '2026-01-05',
    api_endpoint: 'https://globalrec.com/api',
    api_auth_token: 'token_18',
    is_preferred_partner: 1,
    notes: '',
  },
  {
    dca_id: 'DCA-CORP-20',
    agency_name: 'Corporate Debt Solvers',
    short_name: 'Corp Solvers',
    specialization: 'B2B_CASHFLOW',
    regions: 'Metro Cities',
    contact_person: 'Anjali R',
    contact_phone: '+91-9845012364',
    contact_email: 'anjali@corpsolvers.in',
    recovery_rate_overall: 0.84,
    avg_days_to_recovery: 26,
    total_cases_handled: 2800,
    commission_rate: 0.26,
    min_case_amount: 20000,
    max_case_amount: 500000,
    status: 'ACTIVE',
    performance_score: 9,
    sla_first_contact_hours: 24,
    sla_recovery_days: 45,
    created_date: '2025-02-05',
    last_performance_review: '2026-01-06',
    api_endpoint: 'https://corpsolvers.in/api',
    api_auth_token: 'token_20',
    is_preferred_partner: 1,
    notes: '',
  },
];
