const bcrypt = require('bcryptjs');
const { User, Customer, EmailTemplate, DcaAction } = require('../src/models');

const seedData = async () => {
  try {
    // Create users
    const hashedPassword = await bcrypt.hash('password123', 10);
    
    const users = await User.bulkCreate([
      {
        id: 'user-1',
        email: 'admin@fedex.com',
        password: hashedPassword,
        name: 'FedEx Admin',
        role: 'FEDEX_ADMIN',
        avatar: 'https://via.placeholder.com/40',
      },
      {
        id: 'user-2',
        email: 'agent@dca.com',
        password: hashedPassword,
        name: 'DCA Agent',
        role: 'DCA_AGENT',
        avatar: 'https://via.placeholder.com/40',
        agencyId: 'agency_alpha',
      },
    ]);

    // Create customers with all new fields
    const customers = await Customer.bulkCreate([
      {
        id: '1',
        name: 'Acme Logistics Corp',
        accountId: 'FX-883920',
        contactEmail: 'jane.doe@acme.com',
        contactPhone: '+1 (555) 123-4567',
        region: 'North America',
        status: 'Negotiating',
        totalDebt: 12450.00,
        daysOverdue: 15,
        repaymentProbability: 85,
        notes: 'Preferred delivery window: 9AM - 5PM EST.',
        cin: 'U12345ACME2020',
        invoice_amount: 12450.00,
        payment_terms_days: 30,
        service_type: 'GROUND',
        recent_shipments_30d: 12,
        recent_shipments_90d: 45,
        ontime_delivery_rate_hist: 0.95,
        delivery_exceptions_90d: 1,
        past_due_ratio_hist: 0.125,
        dispute_rate_hist: 0.02,
        reminder_count: 1,
        credit_tier: 'LOW_RISK',
        credit_limit: 50000.00,
        outstanding_balance: 12450.00,
        utilization_at_invoice: 0.249,
        analysis_status: 'PENDING',
      },
      {
        id: '2',
        name: 'Globex Inc',
        accountId: 'FX-992104',
        contactEmail: 'billing@globex.io',
        contactPhone: '+1 (555) 987-6543',
        region: 'Europe',
        status: 'New',
        totalDebt: 5200.00,
        daysOverdue: 5,
        repaymentProbability: 92,
        cin: 'U67890GLOB2021',
        invoice_amount: 5200.00,
        payment_terms_days: 30,
        service_type: 'EXPRESS',
        recent_shipments_30d: 8,
        recent_shipments_90d: 28,
        ontime_delivery_rate_hist: 0.98,
        delivery_exceptions_90d: 0,
        past_due_ratio_hist: 0.042,
        dispute_rate_hist: 0.01,
        reminder_count: 0,
        credit_tier: 'LOW_RISK',
        credit_limit: 25000.00,
        outstanding_balance: 5200.00,
        utilization_at_invoice: 0.208,
        analysis_status: 'PENDING',
      },
      {
        id: '3',
        name: 'Soylent Corp',
        accountId: 'FX-445120',
        contactEmail: 'collections@soylent.com',
        contactPhone: '+1 (555) 234-5678',
        region: 'North America',
        status: 'At Risk',
        totalDebt: 28900.00,
        daysOverdue: 45,
        repaymentProbability: 45,
        cin: 'U11111SOYL2019',
        invoice_amount: 28900.00,
        payment_terms_days: 30,
        service_type: 'GROUND',
        recent_shipments_30d: 5,
        recent_shipments_90d: 18,
        ontime_delivery_rate_hist: 0.85,
        delivery_exceptions_90d: 3,
        past_due_ratio_hist: 0.375,
        dispute_rate_hist: 0.08,
        reminder_count: 3,
        credit_tier: 'HIGH_RISK',
        credit_limit: 40000.00,
        outstanding_balance: 28900.00,
        utilization_at_invoice: 0.723,
        analysis_status: 'PENDING',
      },
      {
        id: '4',
        name: 'Initech',
        accountId: 'FX-332110',
        contactEmail: 'peters@initech.com',
        contactPhone: '+1 (555) 888-1234',
        region: 'Asia Pacific',
        status: 'Defaulted',
        totalDebt: 3100.00,
        daysOverdue: 90,
        repaymentProbability: 12,
        assignedToDcaId: 'agency_alpha',
        cin: 'U22222INIT2018',
        invoice_amount: 3100.00,
        payment_terms_days: 30,
        service_type: 'GROUND',
        recent_shipments_30d: 0,
        recent_shipments_90d: 2,
        ontime_delivery_rate_hist: 0.70,
        delivery_exceptions_90d: 5,
        past_due_ratio_hist: 0.75,
        dispute_rate_hist: 0.15,
        reminder_count: 5,
        credit_tier: 'HIGH_RISK',
        credit_limit: 10000.00,
        outstanding_balance: 3100.00,
        utilization_at_invoice: 0.31,
        analysis_status: 'PENDING',
      },
      {
        id: '5',
        name: 'Umbrella Corp',
        accountId: 'FX-881230',
        contactEmail: 'wesker@umbrella.com',
        contactPhone: '+1 (555) 666-7777',
        region: 'North America',
        status: 'Legal Action',
        totalDebt: 150000.00,
        daysOverdue: 120,
        repaymentProbability: 5,
        assignedToDcaId: 'agency_alpha',
        cin: 'U33333UMBR2017',
        invoice_amount: 150000.00,
        payment_terms_days: 30,
        service_type: 'FREIGHT',
        recent_shipments_30d: 0,
        recent_shipments_90d: 0,
        ontime_delivery_rate_hist: 0.60,
        delivery_exceptions_90d: 12,
        past_due_ratio_hist: 1.0,
        dispute_rate_hist: 0.25,
        reminder_count: 8,
        credit_tier: 'HIGH_RISK',
        credit_limit: 200000.00,
        outstanding_balance: 150000.00,
        utilization_at_invoice: 0.75,
        analysis_status: 'PENDING',
      },
      {
        id: '6',
        name: 'TechStart Solutions',
        accountId: 'FX-556677',
        contactEmail: 'finance@techstart.io',
        contactPhone: '+1 (555) 444-5555',
        region: 'North America',
        status: 'Active',
        totalDebt: 8500.00,
        daysOverdue: 0,
        repaymentProbability: 95,
        cin: 'U44444TECH2022',
        invoice_amount: 8500.00,
        payment_terms_days: 30,
        service_type: 'EXPRESS',
        recent_shipments_30d: 15,
        recent_shipments_90d: 52,
        ontime_delivery_rate_hist: 0.99,
        delivery_exceptions_90d: 0,
        past_due_ratio_hist: 0.0,
        dispute_rate_hist: 0.0,
        reminder_count: 0,
        credit_tier: 'LOW_RISK',
        credit_limit: 75000.00,
        outstanding_balance: 8500.00,
        utilization_at_invoice: 0.113,
        analysis_status: 'PENDING',
      },
      {
        id: '7',
        name: 'Global Shipping Partners',
        accountId: 'FX-778899',
        contactEmail: 'accounts@globalship.com',
        contactPhone: '+1 (555) 333-2222',
        region: 'Europe',
        status: 'Review',
        totalDebt: 45000.00,
        daysOverdue: 30,
        repaymentProbability: 65,
        cin: 'U55555GLOB2020',
        invoice_amount: 45000.00,
        payment_terms_days: 45,
        service_type: 'INTERNATIONAL',
        recent_shipments_30d: 20,
        recent_shipments_90d: 65,
        ontime_delivery_rate_hist: 0.88,
        delivery_exceptions_90d: 4,
        past_due_ratio_hist: 0.25,
        dispute_rate_hist: 0.05,
        reminder_count: 2,
        credit_tier: 'MEDIUM_RISK',
        credit_limit: 100000.00,
        outstanding_balance: 45000.00,
        utilization_at_invoice: 0.45,
        analysis_status: 'PENDING',
      },
      {
        id: '8',
        name: 'Metro Express Logistics',
        accountId: 'FX-112233',
        contactEmail: 'billing@metroexpress.net',
        contactPhone: '+1 (555) 777-8888',
        region: 'North America',
        status: 'Negotiating',
        totalDebt: 18900.00,
        daysOverdue: 20,
        repaymentProbability: 75,
        cin: 'U66666METR2021',
        invoice_amount: 18900.00,
        payment_terms_days: 30,
        service_type: 'GROUND',
        recent_shipments_30d: 10,
        recent_shipments_90d: 35,
        ontime_delivery_rate_hist: 0.92,
        delivery_exceptions_90d: 2,
        past_due_ratio_hist: 0.167,
        dispute_rate_hist: 0.03,
        reminder_count: 1,
        credit_tier: 'MEDIUM_RISK',
        credit_limit: 60000.00,
        outstanding_balance: 18900.00,
        utilization_at_invoice: 0.315,
        analysis_status: 'PENDING',
      },
    ]);

    // Create DCA actions
    await DcaAction.bulkCreate([
      {
        id: 'a1',
        customerId: '3',
        type: 'CALL',
        date: new Date('2023-10-20'),
        notes: 'First reminder call. Customer promised payment next week.',
        performedBy: 'System',
      },
      {
        id: 'a2',
        customerId: '4',
        type: 'CALL',
        date: new Date('2023-10-21'),
        notes: 'DCA Initial Contact. No answer.',
        performedBy: 'Agent Smith',
      },
      {
        id: 'a3',
        customerId: '4',
        type: 'VISIT',
        date: new Date('2023-10-23'),
        notes: 'Site visit. Premises appears abandoned.',
        performedBy: 'Agent Smith',
      },
      {
        id: 'a4',
        customerId: '5',
        type: 'LEGAL_NOTICE',
        date: new Date('2023-10-22'),
        notes: 'Legal notice served via certified mail.',
        performedBy: 'Legal Dept',
      },
    ]);

    // Create email templates
    await EmailTemplate.bulkCreate([
      {
        id: 'tpl_1',
        name: 'Q3 Shipping Update',
        subject: 'Important Updates Regarding Your Q3 Shipments',
        description: 'Standard quarterly update regarding rate adjustments and holiday hours.',
        image: 'https://picsum.photos/400/225?random=1',
        body: `Dear {{ContactName}},

We are writing to inform you about upcoming changes to our shipping schedules for the North American region. As a valued partner with {{Status}} status, we want to ensure your logistics operations remain seamless.

Action Required:
Please review your shipment manifest for the week of October 15th via your dashboard.

Best regards,
The FedEx Logistics Team`,
      },
      {
        id: 'tpl_2',
        name: 'Service Alert',
        subject: 'Urgent: Service Interruption Notice',
        description: 'Urgent notification for weather delays or system maintenance.',
        image: 'https://picsum.photos/400/225?random=2',
        body: `URGENT: Service Alert

Dear {{ContactName}},

Due to severe weather conditions, some services in your region may experience delays. We are monitoring the situation closely.

Best regards,
FedEx Operations`,
      },
      {
        id: 'tpl_3',
        name: 'Payment Reminder',
        subject: 'Reminder: Outstanding Balance for Account {{AccountID}}',
        description: 'Soft reminder for upcoming or slightly overdue payments.',
        image: 'https://picsum.photos/400/225?random=3',
        body: `Dear {{ContactName}},

This is a friendly reminder regarding your outstanding balance of {{DebtAmount}}. We value your business and would like to ensure your account remains in good standing.

Best regards,
FedEx Billing`,
      },
    ]);

    console.log('Seed data created successfully!');
  } catch (error) {
    console.error('Error seeding data:', error);
  }
};

module.exports = seedData;
