const sequalize = require('../src/config/database');
const {
  DcaAgency,
  DcaCasesSummary,
  DcaPerformanceByType,
  DcaSlaCompliance,
} = require('../src/models');

const dcaseed = async () => {
  try {
    const dcaAgencies = await DcaAgency.bulkCreate([
      {
        dca_id: 'DCA-AGILE-24',
        agency_name: 'Agile Debt Recovery',
        short_name: 'Agile Rec',
        specialization: 'B2B_CASHFLOW',
        regions: 'North_India',
        contact_person: 'Tarun S',
        contact_phone: '+91-9845012368',
        contact_email: 'tarun@agilerec.in',
        recovery_rate_overall: 0.86,
        avg_days_to_recovery: 25,
        total_cases_handled: 2100,
        commission_rate: 0.26,
        min_case_amount: 10000,
        max_case_amount: 300000,
        status: 'ACTIVE',
        performance_score: 9.2,
        sla_first_contact_hours: 12,
        sla_recovery_days: 40,
        created_date: '2025-04-25',
        last_performance_review: '2026-01-07',
        api_endpoint: 'https://agilerec.in/api',
        api_auth_token: 'token_24',
        is_preferred_partner: 1,
        notes: '',
      },
      {
        dca_id: 'DCA-AVGRES-06',
        agency_name: 'Average Response Collections',
        short_name: 'Avg Response',
        specialization: 'GENERAL',
        regions: 'All India',
        contact_person: 'Priya Sharma',
        contact_phone: '+91-9845012350',
        contact_email: 'priya@avgresponse.in',
        recovery_rate_overall: 0.62,
        avg_days_to_recovery: 35,
        total_cases_handled: 1500,
        commission_rate: 0.24,
        min_case_amount: 1000,
        max_case_amount: 50000,
        status: 'WARNING',
        performance_score: 6.6,
        sla_first_contact_hours: 36,
        sla_recovery_days: 50,
        created_date: '2025-04-15',
        last_performance_review: '2026-01-01',
        api_endpoint: 'https://avgresponse.in/api',
        api_auth_token: 'fedex_dca_token_06',
        is_preferred_partner: 0,
        notes: 'Backlog issues noted',
      },
      {
        dca_id: 'DCA-B2BEXP-05',
        agency_name: 'B2B Collections Experts',
        short_name: 'B2B Experts',
        specialization: 'B2B_CASHFLOW',
        regions: 'Industrial Hubs',
        contact_person: 'Vikram Malhotra',
        contact_phone: '+91-9845012349',
        contact_email: 'vikram@b2bexperts.com',
        recovery_rate_overall: 0.85,
        avg_days_to_recovery: 25,
        total_cases_handled: 3200,
        commission_rate: 0.26,
        min_case_amount: 15000,
        max_case_amount: 1000000,
        status: 'ACTIVE',
        performance_score: 9.1,
        sla_first_contact_hours: 12,
        sla_recovery_days: 45,
        created_date: '2025-03-01',
        last_performance_review: '2026-01-07',
        api_endpoint: 'https://b2bexperts.com/api',
        api_auth_token: 'fedex_dca_token_05',
        is_preferred_partner: 1,
        notes: 'Top performer B2B',
      },
      {
        dca_id: 'DCA-CARGO-38',
        agency_name: 'Cargo Collections',
        short_name: 'Cargo Col',
        specialization: 'FREIGHT_GENERAL',
        regions: 'East_India',
        contact_person: 'Bina A',
        contact_phone: '+91-9845012382',
        contact_email: 'bina@cargocol.in',
        recovery_rate_overall: 0.68,
        avg_days_to_recovery: 33,
        total_cases_handled: 900,
        commission_rate: 0.26,
        min_case_amount: 2000,
        max_case_amount: 80000,
        status: 'ACTIVE',
        performance_score: 7,
        sla_first_contact_hours: 36,
        sla_recovery_days: 45,
        created_date: '2025-06-22',
        last_performance_review: '2026-01-02',
        api_endpoint: 'https://cargocol.in/api',
        api_auth_token: 'token_38',
        is_preferred_partner: 0,
        notes: '',
      },
      {
        dca_id: 'DCA-CITY-25',
        agency_name: 'City Limits Recovery',
        short_name: 'City Lim',
        specialization: 'B2C_AVOIDANCE',
        regions: 'Metro Cities',
        contact_person: 'Meera K',
        contact_phone: '+91-9845012369',
        contact_email: 'meera@citylim.in',
        recovery_rate_overall: 0.59,
        avg_days_to_recovery: 28,
        total_cases_handled: 9000,
        commission_rate: 0.27,
        min_case_amount: 500,
        max_case_amount: 10000,
        status: 'ACTIVE',
        performance_score: 7.3,
        sla_first_contact_hours: 4,
        sla_recovery_days: 25,
        created_date: '2025-05-30',
        last_performance_review: '2026-01-03',
        api_endpoint: 'https://citylim.in/api',
        api_auth_token: 'token_25',
        is_preferred_partner: 0,
        notes: '',
      },
      {
        dca_id: 'DCA-CORE-43',
        agency_name: 'Core Debt Solutions',
        short_name: 'Core Sol',
        specialization: 'B2B_CASHFLOW',
        regions: 'West_India',
        contact_person: 'Shilpa B',
        contact_phone: '+91-9845012387',
        contact_email: 'shilpa@coresol.in',
        recovery_rate_overall: 0.85,
        avg_days_to_recovery: 25,
        total_cases_handled: 1800,
        commission_rate: 0.26,
        min_case_amount: 10000,
        max_case_amount: 250000,
        status: 'ACTIVE',
        performance_score: 9,
        sla_first_contact_hours: 12,
        sla_recovery_days: 42,
        created_date: '2025-04-12',
        last_performance_review: '2026-01-06',
        api_endpoint: 'https://coresol.in/api',
        api_auth_token: 'token_43',
        is_preferred_partner: 1,
        notes: '',
      },
      {
        dca_id: 'DCA-CORP-20',
        agency_name: 'Corporate Debt Solvers',
        short_name: 'Corp Solvers',
        specialization: 'B2B_CASHFLOW',
        regions: 'Metro Cities',
        contact_person: 'Anjali R',
        contact_phone: '+91-9845012364',
        contact_email: 'anjali@corpsolvers.in',
        recovery_rate_overall: 0.84,
        avg_days_to_recovery: 26,
        total_cases_handled: 2800,
        commission_rate: 0.26,
        min_case_amount: 20000,
        max_case_amount: 500000,
        status: 'ACTIVE',
        performance_score: 9,
        sla_first_contact_hours: 24,
        sla_recovery_days: 45,
        created_date: '2025-02-05',
        last_performance_review: '2026-01-06',
        api_endpoint: 'https://corpsolvers.in/api',
        api_auth_token: 'token_20',
        is_preferred_partner: 1,
        notes: '',
      },
      {
        dca_id: 'DCA-CUSTIND-01',
        agency_name: 'Customs Recovery Specialists India Pvt Ltd',
        short_name: 'Customs Recovery India',
        specialization: 'CUSTOMS_DISPUTE',
        regions: 'South_India,North_India',
        contact_person: 'Ravi Kumar',
        contact_phone: '+91-9845012345',
        contact_email: 'ravi@customsrecovery.in',
        recovery_rate_overall: 0.78,
        avg_days_to_recovery: 28,
        total_cases_handled: 2456,
        commission_rate: 0.28,
        min_case_amount: 5000,
        max_case_amount: 500000,
        status: 'ACTIVE',
        performance_score: 8.4,
        sla_first_contact_hours: 24,
        sla_recovery_days: 45,
        created_date: '2025-01-15',
        last_performance_review: '2026-01-07',
        api_endpoint: 'https://dca-customsindia.com/api',
        api_auth_token: 'fedex_dca_token_01',
        is_preferred_partner: 1,
        notes: 'Excellent on customs disputes',
      },
      {
        dca_id: 'DCA-DELTA-48',
        agency_name: 'Delta Force Recovery',
        short_name: 'Delta Force',
        specialization: 'FREIGHT_GENERAL',
        regions: 'North_India',
        contact_person: 'Sunil J',
        contact_phone: '+91-9845012392',
        contact_email: 'sunil@deltaforce.in',
        recovery_rate_overall: 0.81,
        avg_days_to_recovery: 23,
        total_cases_handled: 2600,
        commission_rate: 0.25,
        min_case_amount: 2000,
        max_case_amount: 130000,
        status: 'ACTIVE',
        performance_score: 8.6,
        sla_first_contact_hours: 24,
        sla_recovery_days: 40,
        created_date: '2025-02-28',
        last_performance_review: '2026-01-06',
        api_endpoint: 'https://deltaforce.in/api',
        api_auth_token: 'token_48',
        is_preferred_partner: 0,
        notes: '',
      },
      {
        dca_id: 'DCA-DIGITAL-36',
        agency_name: 'Digital Debt Works',
        short_name: 'Digital DW',
        specialization: 'ADMIN_FEES',
        regions: 'All India',
        contact_person: 'Simran E',
        contact_phone: '+91-9845012380',
        contact_email: 'simran@digitaldw.in',
        recovery_rate_overall: 0.66,
        avg_days_to_recovery: 19,
        total_cases_handled: 7000,
        commission_rate: 0.22,
        min_case_amount: 500,
        max_case_amount: 15000,
        status: 'ACTIVE',
        performance_score: 7.2,
        sla_first_contact_hours: 48,
        sla_recovery_days: 28,
        created_date: '2025-04-02',
        last_performance_review: '2026-01-01',
        api_endpoint: 'https://digitaldw.in/api',
        api_auth_token: 'token_36',
        is_preferred_partner: 0,
        notes: '',
      },
      {
        dca_id: 'DCA-DISPUTE-35',
        agency_name: 'Dispute Resolution Ctr',
        short_name: 'DRC',
        specialization: 'HIGH_COMPLEXITY',
        regions: 'West_India',
        contact_person: 'Manoj F',
        contact_phone: '+91-9845012379',
        contact_email: 'manoj@drc.in',
        recovery_rate_overall: 0.7,
        avg_days_to_recovery: 43,
        total_cases_handled: 500,
        commission_rate: 0.34,
        min_case_amount: 50000,
        max_case_amount: 1500000,
        status: 'ACTIVE',
        performance_score: 7.6,
        sla_first_contact_hours: 24,
        sla_recovery_days: 60,
        created_date: '2025-03-08',
        last_performance_review: '2026-01-04',
        api_endpoint: 'https://drc.in/api',
        api_auth_token: 'token_35',
        is_preferred_partner: 0,
        notes: '',
      },
      {
        dca_id: 'DCA-EAST-13',
        agency_name: 'Eastern Freight Solutions',
        short_name: 'East Sol',
        specialization: 'FREIGHT_GENERAL',
        regions: 'East_India',
        contact_person: 'Rahul M',
        contact_phone: '+91-9845012357',
        contact_email: 'rahul@eastsol.in',
        recovery_rate_overall: 0.69,
        avg_days_to_recovery: 32,
        total_cases_handled: 1100,
        commission_rate: 0.26,
        min_case_amount: 2000,
        max_case_amount: 100000,
        status: 'WARNING',
        performance_score: 6.8,
        sla_first_contact_hours: 36,
        sla_recovery_days: 45,
        created_date: '2025-06-15',
        last_performance_review: '2026-01-01',
        api_endpoint: 'https://eastsol.in/api',
        api_auth_token: 'token_13',
        is_preferred_partner: 0,
        notes: 'Slow response times',
      },
      {
        dca_id: 'DCA-ELITE-46',
        agency_name: 'Elite Recovery',
        short_name: 'Elite Rec',
        specialization: 'HIGH_COMPLEXITY',
        regions: 'South_India',
        contact_person: 'Arjun L',
        contact_phone: '+91-9845012390',
        contact_email: 'arjun@eliterec.in',
        recovery_rate_overall: 0.71,
        avg_days_to_recovery: 46,
        total_cases_handled: 300,
        commission_rate: 0.35,
        min_case_amount: 75000,
        max_case_amount: 3000000,
        status: 'ACTIVE',
        performance_score: 7.7,
        sla_first_contact_hours: 24,
        sla_recovery_days: 60,
        created_date: '2025-07-10',
        last_performance_review: '2026-01-05',
        api_endpoint: 'https://eliterec.in/api',
        api_auth_token: 'token_46',
        is_preferred_partner: 1,
        notes: '',
      },
      {
        dca_id: 'DCA-ENTERP-10',
        agency_name: 'Enterprise Debt Solutions',
        short_name: 'Ent Solutions',
        specialization: 'HIGH_VALUE_B2B',
        regions: 'Metro Cities',
        contact_person: 'Robert D',
        contact_phone: '+91-9845012354',
        contact_email: 'robert@entsol.com',
        recovery_rate_overall: 0.79,
        avg_days_to_recovery: 33,
        total_cases_handled: 1100,
        commission_rate: 0.29,
        min_case_amount: 500000,
        max_case_amount: 10000000,
        status: 'ACTIVE',
        performance_score: 8.5,
        sla_first_contact_hours: 12,
        sla_recovery_days: 60,
        created_date: '2025-03-15',
        last_performance_review: '2026-01-06',
        api_endpoint: 'https://entsol.com/api',
        api_auth_token: 'fedex_dca_token_10',
        is_preferred_partner: 1,
        notes: 'Strategic partner',
      },
      {
        dca_id: 'DCA-EXPRESS-21',
        agency_name: 'Express Recovery Ltd',
        short_name: 'Express Rec',
        specialization: 'FREIGHT_GENERAL',
        regions: 'South_India',
        contact_person: 'Kiran P',
        contact_phone: '+91-9845012365',
        contact_email: 'kiran@expressrec.in',
        recovery_rate_overall: 0.77,
        avg_days_to_recovery: 23,
        total_cases_handled: 3500,
        commission_rate: 0.25,
        min_case_amount: 1500,
        max_case_amount: 100000,
        status: 'ACTIVE',
        performance_score: 8.2,
        sla_first_contact_hours: 24,
        sla_recovery_days: 35,
        created_date: '2025-06-20',
        last_performance_review: '2026-01-04',
        api_endpoint: 'https://expressrec.in/api',
        api_auth_token: 'token_21',
        is_preferred_partner: 0,
        notes: '',
      },
      {
        dca_id: 'DCA-FAST-31',
        agency_name: 'FastTrack Collections',
        short_name: 'FastTrack',
        specialization: 'CUSTOMS_DISPUTE',
        regions: 'South_India',
        contact_person: 'Leela V',
        contact_phone: '+91-9845012375',
        contact_email: 'leela@fasttrack.in',
        recovery_rate_overall: 0.77,
        avg_days_to_recovery: 27,
        total_cases_handled: 2300,
        commission_rate: 0.28,
        min_case_amount: 5000,
        max_case_amount: 350000,
        status: 'ACTIVE',
        performance_score: 8.3,
        sla_first_contact_hours: 24,
        sla_recovery_days: 42,
        created_date: '2025-06-25',
        last_performance_review: '2026-01-05',
        api_endpoint: 'https://fasttrack.in/api',
        api_auth_token: 'token_31',
        is_preferred_partner: 0,
        notes: '',
      },
      {
        dca_id: 'DCA-FIELD-08',
        agency_name: 'Field Collection Specialists',
        short_name: 'Field Specs',
        specialization: 'UNREACHABLE',
        regions: 'Tier2 Cities',
        contact_person: 'Amit Verma',
        contact_phone: '+91-9845012352',
        contact_email: 'amit@fieldspecs.in',
        recovery_rate_overall: 0.71,
        avg_days_to_recovery: 38,
        total_cases_handled: 950,
        commission_rate: 0.32,
        min_case_amount: 5000,
        max_case_amount: 200000,
        status: 'ACTIVE',
        performance_score: 7.8,
        sla_first_contact_hours: 48,
        sla_recovery_days: 55,
        created_date: '2025-02-28',
        last_performance_review: '2026-01-07',
        api_endpoint: 'https://fieldspecs.in/api',
        api_auth_token: 'fedex_dca_token_08',
        is_preferred_partner: 0,
        notes: 'Good for physical visits',
      },
      {
        dca_id: 'DCA-FRTGEN-02',
        agency_name: 'Freight Collections Nationwide',
        short_name: 'Freight Col',
        specialization: 'FREIGHT_GENERAL',
        regions: 'All India',
        contact_person: 'Anita Desai',
        contact_phone: '+91-9845012346',
        contact_email: 'anita@freightcol.in',
        recovery_rate_overall: 0.82,
        avg_days_to_recovery: 22,
        total_cases_handled: 5100,
        commission_rate: 0.25,
        min_case_amount: 2000,
        max_case_amount: 100000,
        status: 'ACTIVE',
        performance_score: 8.8,
        sla_first_contact_hours: 24,
        sla_recovery_days: 40,
        created_date: '2025-01-20',
        last_performance_review: '2026-01-05',
        api_endpoint: 'https://api.freightcol.in/v1',
        api_auth_token: 'fedex_dca_token_02',
        is_preferred_partner: 1,
        notes: 'Best for general freight',
      },
      {
        dca_id: 'DCA-GLOBAL-18',
        agency_name: 'Global Trade Recovery',
        short_name: 'Global Rec',
        specialization: 'CUSTOMS_DISPUTE',
        regions: 'All India',
        contact_person: 'John D',
        contact_phone: '+91-9845012362',
        contact_email: 'john@globalrec.com',
        recovery_rate_overall: 0.8,
        avg_days_to_recovery: 27,
        total_cases_handled: 3100,
        commission_rate: 0.29,
        min_case_amount: 10000,
        max_case_amount: 750000,
        status: 'ACTIVE',
        performance_score: 8.7,
        sla_first_contact_hours: 24,
        sla_recovery_days: 40,
        created_date: '2025-01-25',
        last_performance_review: '2026-01-05',
        api_endpoint: 'https://globalrec.com/api',
        api_auth_token: 'token_18',
        is_preferred_partner: 1,
        notes: '',
      },
      {
        dca_id: 'DCA-HEAVY-34',
        agency_name: 'Heavy Industry Collections',
        short_name: 'Heavy Ind',
        specialization: 'B2B_CASHFLOW',
        regions: 'Industrial Hubs',
        contact_person: 'Kamal Y',
        contact_phone: '+91-9845012378',
        contact_email: 'kamal@heavyind.in',
        recovery_rate_overall: 0.83,
        avg_days_to_recovery: 26,
        total_cases_handled: 1500,
        commission_rate: 0.26,
        min_case_amount: 15000,
        max_case_amount: 500000,
        status: 'ACTIVE',
        performance_score: 8.9,
        sla_first_contact_hours: 12,
        sla_recovery_days: 45,
        created_date: '2025-02-12',
        last_performance_review: '2026-01-06',
        api_endpoint: 'https://heavyind.in/api',
        api_auth_token: 'token_34',
        is_preferred_partner: 1,
        notes: '',
      },
      {
        dca_id: 'DCA-LEGAL-04',
        agency_name: 'Legal Debt Recovery Partners',
        short_name: 'LDR Partners',
        specialization: 'HIGH_COMPLEXITY',
        regions: 'All India',
        contact_person: 'Sanjay Gupta',
        contact_phone: '+91-9845012348',
        contact_email: 'legal@ldrpartners.in',
        recovery_rate_overall: 0.68,
        avg_days_to_recovery: 45,
        total_cases_handled: 850,
        commission_rate: 0.35,
        min_case_amount: 100000,
        max_case_amount: 5000000,
        status: 'ACTIVE',
        performance_score: 7.5,
        sla_first_contact_hours: 24,
        sla_recovery_days: 60,
        created_date: '2025-01-10',
        last_performance_review: '2026-01-06',
        api_endpoint: 'https://api.ldrpartners.in',
        api_auth_token: 'fedex_dca_token_04',
        is_preferred_partner: 1,
        notes: 'Use for litigation cases',
      },
      {
        dca_id: 'DCA-LINK-41',
        agency_name: 'Link Collections',
        short_name: 'Link Col',
        specialization: 'FREIGHT_GENERAL',
        regions: 'South_India',
        contact_person: 'Varun C',
        contact_phone: '+91-9845012385',
        contact_email: 'varun@linkcol.in',
        recovery_rate_overall: 0.78,
        avg_days_to_recovery: 22,
        total_cases_handled: 2500,
        commission_rate: 0.25,
        min_case_amount: 2000,
        max_case_amount: 100000,
        status: 'ACTIVE',
        performance_score: 8.3,
        sla_first_contact_hours: 24,
        sla_recovery_days: 38,
        created_date: '2025-02-18',
        last_performance_review: '2026-01-04',
        api_endpoint: 'https://linkcol.in/api',
        api_auth_token: 'token_41',
        is_preferred_partner: 0,
        notes: '',
      },
      {
        dca_id: 'DCA-LOCAL-19',
        agency_name: 'Local Reach Agents',
        short_name: 'Local Reach',
        specialization: 'UNREACHABLE',
        regions: 'Tier3 Cities',
        contact_person: 'Vijay B',
        contact_phone: '+91-9845012363',
        contact_email: 'vijay@localreach.in',
        recovery_rate_overall: 0.65,
        avg_days_to_recovery: 41,
        total_cases_handled: 750,
        commission_rate: 0.33,
        min_case_amount: 2000,
        max_case_amount: 50000,
        status: 'ACTIVE',
        performance_score: 7,
        sla_first_contact_hours: 48,
        sla_recovery_days: 60,
        created_date: '2025-05-10',
        last_performance_review: '2026-01-02',
        api_endpoint: 'https://localreach.in/api',
        api_auth_token: 'token_19',
        is_preferred_partner: 0,
        notes: '',
      },
      {
        dca_id: 'DCA-LOGISTIC-28',
        agency_name: 'Logistics Debt Mgmt',
        short_name: 'Logistics DM',
        specialization: 'FREIGHT_GENERAL',
        regions: 'North_India',
        contact_person: 'Vikas J',
        contact_phone: '+91-9845012372',
        contact_email: 'vikas@logisticsdm.in',
        recovery_rate_overall: 0.79,
        avg_days_to_recovery: 24,
        total_cases_handled: 2800,
        commission_rate: 0.25,
        min_case_amount: 2000,
        max_case_amount: 120000,
        status: 'ACTIVE',
        performance_score: 8.4,
        sla_first_contact_hours: 24,
        sla_recovery_days: 40,
        created_date: '2025-03-30',
        last_performance_review: '2026-01-04',
        api_endpoint: 'https://logisticsdm.in/api',
        api_auth_token: 'token_28',
        is_preferred_partner: 0,
        notes: '',
      },
      {
        dca_id: 'DCA-METRO-45',
        agency_name: 'Metro Claims',
        short_name: 'Metro Cl',
        specialization: 'ADMIN_FEES',
        regions: 'Metro Cities',
        contact_person: 'Kavita M',
        contact_phone: '+91-9845012389',
        contact_email: 'kavita@metrocl.in',
        recovery_rate_overall: 0.67,
        avg_days_to_recovery: 18,
        total_cases_handled: 4800,
        commission_rate: 0.22,
        min_case_amount: 500,
        max_case_amount: 10000,
        status: 'ACTIVE',
        performance_score: 7.3,
        sla_first_contact_hours: 48,
        sla_recovery_days: 28,
        created_date: '2025-06-05',
        last_performance_review: '2026-01-03',
        api_endpoint: 'https://metrocl.in/api',
        api_auth_token: 'token_45',
        is_preferred_partner: 0,
        notes: '',
      },
      {
        dca_id: 'DCA-MICRO-29',
        agency_name: 'Micro Finance Recovery',
        short_name: 'Micro Fin',
        specialization: 'ADMIN_FEES',
        regions: 'East_India',
        contact_person: 'Pooja T',
        contact_phone: '+91-9845012373',
        contact_email: 'pooja@microfin.in',
        recovery_rate_overall: 0.64,
        avg_days_to_recovery: 20,
        total_cases_handled: 6000,
        commission_rate: 0.22,
        min_case_amount: 500,
        max_case_amount: 12000,
        status: 'ACTIVE',
        performance_score: 7,
        sla_first_contact_hours: 48,
        sla_recovery_days: 30,
        created_date: '2025-04-10',
        last_performance_review: '2026-01-01',
        api_endpoint: 'https://microfin.in/api',
        api_auth_token: 'token_29',
        is_preferred_partner: 0,
        notes: '',
      },
      {
        dca_id: 'DCA-NATION-32',
        agency_name: 'National Freight Rec',
        short_name: 'National Rec',
        specialization: 'FREIGHT_GENERAL',
        regions: 'All India',
        contact_person: 'Gopal H',
        contact_phone: '+91-9845012376',
        contact_email: 'gopal@nationalrec.in',
        recovery_rate_overall: 0.8,
        avg_days_to_recovery: 23,
        total_cases_handled: 4200,
        commission_rate: 0.25,
        min_case_amount: 2000,
        max_case_amount: 150000,
        status: 'ACTIVE',
        performance_score: 8.5,
        sla_first_contact_hours: 24,
        sla_recovery_days: 38,
        created_date: '2025-07-20',
        last_performance_review: '2026-01-03',
        api_endpoint: 'https://nationalrec.in/api',
        api_auth_token: 'token_32',
        is_preferred_partner: 1,
        notes: '',
      },
      {
        dca_id: 'DCA-NORTH-11',
        agency_name: 'Northern Territories Recovery',
        short_name: 'North Rec',
        specialization: 'CUSTOMS_DISPUTE',
        regions: 'North_India',
        contact_person: 'Manish T',
        contact_phone: '+91-9845012355',
        contact_email: 'manish@northrec.in',
        recovery_rate_overall: 0.74,
        avg_days_to_recovery: 30,
        total_cases_handled: 1800,
        commission_rate: 0.28,
        min_case_amount: 5000,
        max_case_amount: 300000,
        status: 'ACTIVE',
        performance_score: 7.9,
        sla_first_contact_hours: 24,
        sla_recovery_days: 45,
        created_date: '2025-06-01',
        last_performance_review: '2026-01-02',
        api_endpoint: 'https://northrec.in/api',
        api_auth_token: 'token_11',
        is_preferred_partner: 0,
        notes: '',
      },
      {
        dca_id: 'DCA-OMEGA-47',
        agency_name: 'Omega Collections',
        short_name: 'Omega Col',
        specialization: 'CUSTOMS_DISPUTE',
        regions: 'West_India',
        contact_person: 'Praveen K',
        contact_phone: '+91-9845012391',
        contact_email: 'praveen@omegacol.in',
        recovery_rate_overall: 0.76,
        avg_days_to_recovery: 28,
        total_cases_handled: 1100,
        commission_rate: 0.28,
        min_case_amount: 5000,
        max_case_amount: 220000,
        status: 'ACTIVE',
        performance_score: 8.1,
        sla_first_contact_hours: 24,
        sla_recovery_days: 45,
        created_date: '2025-01-22',
        last_performance_review: '2026-01-04',
        api_endpoint: 'https://omegacol.in/api',
        api_auth_token: 'token_47',
        is_preferred_partner: 0,
        notes: '',
      },
      {
        dca_id: 'DCA-PARTNER-30',
        agency_name: 'Partner Recovery Group',
        short_name: 'Partner Grp',
        specialization: 'HIGH_VALUE_B2B',
        regions: 'All India',
        contact_person: 'Nikhil O',
        contact_phone: '+91-9845012374',
        contact_email: 'nikhil@partnergrp.in',
        recovery_rate_overall: 0.82,
        avg_days_to_recovery: 32,
        total_cases_handled: 900,
        commission_rate: 0.29,
        min_case_amount: 100000,
        max_case_amount: 8000000,
        status: 'ACTIVE',
        performance_score: 8.8,
        sla_first_contact_hours: 12,
        sla_recovery_days: 55,
        created_date: '2025-05-05',
        last_performance_review: '2026-01-07',
        api_endpoint: 'https://partnergrp.in/api',
        api_auth_token: 'token_30',
        is_preferred_partner: 1,
        notes: '',
      },
      {
        dca_id: 'DCA-PENREC-09',
        agency_name: 'Penalty Recovery Unit',
        short_name: 'Penalty Unit',
        specialization: 'PENALTIES',
        regions: 'All India',
        contact_person: 'Neha Kapoor',
        contact_phone: '+91-9845012353',
        contact_email: 'neha@penaltyunit.com',
        recovery_rate_overall: 0.55,
        avg_days_to_recovery: 42,
        total_cases_handled: 600,
        commission_rate: 0.3,
        min_case_amount: 2000,
        max_case_amount: 50000,
        status: 'SUSPENDED',
        performance_score: 6.5,
        sla_first_contact_hours: 24,
        sla_recovery_days: 45,
        created_date: '2025-01-05',
        last_performance_review: '2025-12-20',
        api_endpoint: 'https://penaltyunit.com/api',
        api_auth_token: 'fedex_dca_token_09',
        is_preferred_partner: 0,
        notes: 'Under review for compliance',
      },
      {
        dca_id: 'DCA-PREMIUM-15',
        agency_name: 'Premium Debt Management',
        short_name: 'Premium DM',
        specialization: 'HIGH_VALUE_B2B',
        regions: 'Metro Cities',
        contact_person: 'Sarah J',
        contact_phone: '+91-9845012359',
        contact_email: 'sarah@premiumdm.com',
        recovery_rate_overall: 0.83,
        avg_days_to_recovery: 31,
        total_cases_handled: 600,
        commission_rate: 0.3,
        min_case_amount: 250000,
        max_case_amount: 5000000,
        status: 'ACTIVE',
        performance_score: 8.9,
        sla_first_contact_hours: 12,
        sla_recovery_days: 50,
        created_date: '2025-02-15',
        last_performance_review: '2026-01-06',
        api_endpoint: 'https://premiumdm.com/api',
        api_auth_token: 'token_15',
        is_preferred_partner: 1,
        notes: '',
      },
      {
        dca_id: 'DCA-PRIME-40',
        agency_name: 'Prime B2B Recovery',
        short_name: 'Prime B2B',
        specialization: 'HIGH_VALUE_B2B',
        regions: 'Metro Cities',
        contact_person: 'Deepa X',
        contact_phone: '+91-9845012384',
        contact_email: 'deepa@primeb2b.in',
        recovery_rate_overall: 0.81,
        avg_days_to_recovery: 32,
        total_cases_handled: 750,
        commission_rate: 0.29,
        min_case_amount: 150000,
        max_case_amount: 4000000,
        status: 'ACTIVE',
        performance_score: 8.7,
        sla_first_contact_hours: 12,
        sla_recovery_days: 55,
        created_date: '2025-01-12',
        last_performance_review: '2026-01-07',
        api_endpoint: 'https://primeb2b.in/api',
        api_auth_token: 'token_40',
        is_preferred_partner: 1,
        notes: '',
      },
      {
        dca_id: 'DCA-PRIORITY-27',
        agency_name: 'Priority Collections',
        short_name: 'Priority Col',
        specialization: 'CUSTOMS_DISPUTE',
        regions: 'West_India',
        contact_person: 'Suresh I',
        contact_phone: '+91-9845012371',
        contact_email: 'suresh@prioritycol.in',
        recovery_rate_overall: 0.75,
        avg_days_to_recovery: 29,
        total_cases_handled: 1600,
        commission_rate: 0.28,
        min_case_amount: 5000,
        max_case_amount: 250000,
        status: 'ACTIVE',
        performance_score: 8,
        sla_first_contact_hours: 24,
        sla_recovery_days: 45,
        created_date: '2025-02-25',
        last_performance_review: '2026-01-06',
        api_endpoint: 'https://prioritycol.in/api',
        api_auth_token: 'token_27',
        is_preferred_partner: 0,
        notes: '',
      },
      {
        dca_id: 'DCA-RAPID-16',
        agency_name: 'Rapid Response Agency',
        short_name: 'Rapid Ag',
        specialization: 'ADMIN_FEES',
        regions: 'South_India',
        contact_person: 'Mohan L',
        contact_phone: '+91-9845012360',
        contact_email: 'mohan@rapidag.in',
        recovery_rate_overall: 0.7,
        avg_days_to_recovery: 19,
        total_cases_handled: 4500,
        commission_rate: 0.22,
        min_case_amount: 1000,
        max_case_amount: 25000,
        status: 'ACTIVE',
        performance_score: 7.5,
        sla_first_contact_hours: 24,
        sla_recovery_days: 30,
        created_date: '2025-03-20',
        last_performance_review: '2026-01-04',
        api_endpoint: 'https://rapidag.in/api',
        api_auth_token: 'token_16',
        is_preferred_partner: 0,
        notes: '',
      },
      {
        dca_id: 'DCA-RETAIL-33',
        agency_name: 'Retail Debt Solutions',
        short_name: 'Retail Sol',
        specialization: 'B2C_AVOIDANCE',
        regions: 'Metro Cities',
        contact_person: 'Tina U',
        contact_phone: '+91-9845012377',
        contact_email: 'tina@retailsol.in',
        recovery_rate_overall: 0.57,
        avg_days_to_recovery: 30,
        total_cases_handled: 12000,
        commission_rate: 0.27,
        min_case_amount: 500,
        max_case_amount: 8000,
        status: 'WARNING',
        performance_score: 6.8,
        sla_first_contact_hours: 4,
        sla_recovery_days: 30,
        created_date: '2025-01-18',
        last_performance_review: '2026-01-02',
        api_endpoint: 'https://retailsol.in/api',
        api_auth_token: 'token_33',
        is_preferred_partner: 0,
        notes: '',
      },
      {
        dca_id: 'DCA-RURAL-26',
        agency_name: 'Rural Connect Agency',
        short_name: 'Rural Con',
        specialization: 'UNREACHABLE',
        regions: 'Rural Areas',
        contact_person: 'Ashok N',
        contact_phone: '+91-9845012370',
        contact_email: 'ashok@ruralcon.in',
        recovery_rate_overall: 0.61,
        avg_days_to_recovery: 40,
        total_cases_handled: 500,
        commission_rate: 0.33,
        min_case_amount: 1000,
        max_case_amount: 40000,
        status: 'ACTIVE',
        performance_score: 6.9,
        sla_first_contact_hours: 72,
        sla_recovery_days: 60,
        created_date: '2025-01-30',
        last_performance_review: '2026-01-02',
        api_endpoint: 'https://ruralcon.in/api',
        api_auth_token: 'token_26',
        is_preferred_partner: 0,
        notes: '',
      },
      {
        dca_id: 'DCA-SECURE-17',
        agency_name: 'Secure Financial Services',
        short_name: 'Secure Fin',
        specialization: 'DISPUTE',
        regions: 'North_India',
        contact_person: 'Deepak S',
        contact_phone: '+91-9845012361',
        contact_email: 'deepak@securefin.in',
        recovery_rate_overall: 0.76,
        avg_days_to_recovery: 29,
        total_cases_handled: 1900,
        commission_rate: 0.27,
        min_case_amount: 5000,
        max_case_amount: 200000,
        status: 'ACTIVE',
        performance_score: 8.1,
        sla_first_contact_hours: 24,
        sla_recovery_days: 45,
        created_date: '2025-04-05',
        last_performance_review: '2026-01-07',
        api_endpoint: 'https://securefin.in/api',
        api_auth_token: 'token_17',
        is_preferred_partner: 0,
        notes: '',
      },
      {
        dca_id: 'DCA-SIGMA-49',
        agency_name: 'Sigma Debt Mgmt',
        short_name: 'Sigma DM',
        specialization: 'B2B_CASHFLOW',
        regions: 'East_India',
        contact_person: 'Rekha H',
        contact_phone: '+91-9845012393',
        contact_email: 'rekha@sigmadm.in',
        recovery_rate_overall: 0.82,
        avg_days_to_recovery: 27,
        total_cases_handled: 900,
        commission_rate: 0.26,
        min_case_amount: 12000,
        max_case_amount: 150000,
        status: 'ACTIVE',
        performance_score: 8.7,
        sla_first_contact_hours: 12,
        sla_recovery_days: 45,
        created_date: '2025-03-18',
        last_performance_review: '2026-01-02',
        api_endpoint: 'https://sigmadm.in/api',
        api_auth_token: 'token_49',
        is_preferred_partner: 0,
        notes: '',
      },
      {
        dca_id: 'DCA-SMALLCL-03',
        agency_name: 'Micro Claims Recovery',
        short_name: 'MicroClaims',
        specialization: 'ADMIN_FEES',
        regions: 'Metro Cities',
        contact_person: 'Rajesh Singh',
        contact_phone: '+91-9845012347',
        contact_email: 'rajesh@microclaims.com',
        recovery_rate_overall: 0.65,
        avg_days_to_recovery: 18,
        total_cases_handled: 12500,
        commission_rate: 0.22,
        min_case_amount: 500,
        max_case_amount: 10000,
        status: 'WARNING',
        performance_score: 6.9,
        sla_first_contact_hours: 48,
        sla_recovery_days: 30,
        created_date: '2025-02-10',
        last_performance_review: '2026-01-02',
        api_endpoint: 'https://microclaims.com/api',
        api_auth_token: 'fedex_dca_token_03',
        is_preferred_partner: 0,
        notes: 'High volume low value',
      },
      {
        dca_id: 'DCA-SMSHUNT-07',
        agency_name: 'SMS Hunter Recovery',
        short_name: 'SMS Hunter',
        specialization: 'B2C_AVOIDANCE',
        regions: 'Urban Areas',
        contact_person: 'Karthik R',
        contact_phone: '+91-9845012351',
        contact_email: 'karthik@smshunter.io',
        recovery_rate_overall: 0.58,
        avg_days_to_recovery: 29,
        total_cases_handled: 14500,
        commission_rate: 0.27,
        min_case_amount: 500,
        max_case_amount: 5000,
        status: 'ACTIVE',
        performance_score: 7.2,
        sla_first_contact_hours: 4,
        sla_recovery_days: 30,
        created_date: '2025-05-20',
        last_performance_review: '2026-01-04',
        api_endpoint: 'https://api.smshunter.io',
        api_auth_token: 'fedex_dca_token_07',
        is_preferred_partner: 0,
        notes: 'Tech-first approach',
      },
      {
        dca_id: 'DCA-SWIFT-44',
        agency_name: 'Swift Action Agency',
        short_name: 'Swift Act',
        specialization: 'PENALTIES',
        regions: 'All India',
        contact_person: 'Gaurav N',
        contact_phone: '+91-9845012388',
        contact_email: 'gaurav@swiftact.in',
        recovery_rate_overall: 0.56,
        avg_days_to_recovery: 41,
        total_cases_handled: 500,
        commission_rate: 0.3,
        min_case_amount: 2000,
        max_case_amount: 40000,
        status: 'WARNING',
        performance_score: 6.6,
        sla_first_contact_hours: 24,
        sla_recovery_days: 45,
        created_date: '2025-05-30',
        last_performance_review: '2026-01-02',
        api_endpoint: 'https://swiftact.in/api',
        api_auth_token: 'token_44',
        is_preferred_partner: 0,
        notes: '',
      },
      {
        dca_id: 'DCA-TASK-42',
        agency_name: 'Task Force Recovery',
        short_name: 'Task Force',
        specialization: 'UNREACHABLE',
        regions: 'Tier2 Cities',
        contact_person: 'Anil V',
        contact_phone: '+91-9845012386',
        contact_email: 'anil@taskforce.in',
        recovery_rate_overall: 0.69,
        avg_days_to_recovery: 39,
        total_cases_handled: 800,
        commission_rate: 0.32,
        min_case_amount: 3000,
        max_case_amount: 100000,
        status: 'ACTIVE',
        performance_score: 7.5,
        sla_first_contact_hours: 48,
        sla_recovery_days: 55,
        created_date: '2025-03-25',
        last_performance_review: '2026-01-01',
        api_endpoint: 'https://taskforce.in/api',
        api_auth_token: 'token_42',
        is_preferred_partner: 0,
        notes: '',
      },
      {
        dca_id: 'DCA-TECH-14',
        agency_name: 'TechDriven Recovery',
        short_name: 'Tech Rec',
        specialization: 'B2C_AVOIDANCE',
        regions: 'All India',
        contact_person: 'Arun K',
        contact_phone: '+91-9845012358',
        contact_email: 'arun@techrec.io',
        recovery_rate_overall: 0.6,
        avg_days_to_recovery: 20,
        total_cases_handled: 8500,
        commission_rate: 0.23,
        min_case_amount: 500,
        max_case_amount: 10000,
        status: 'ACTIVE',
        performance_score: 7.1,
        sla_first_contact_hours: 4,
        sla_recovery_days: 25,
        created_date: '2025-07-01',
        last_performance_review: '2026-01-05',
        api_endpoint: 'https://techrec.io/api',
        api_auth_token: 'token_14',
        is_preferred_partner: 0,
        notes: 'Automated calls only',
      },
      {
        dca_id: 'DCA-TRUST-23',
        agency_name: 'Trust Legal Services',
        short_name: 'Trust Legal',
        specialization: 'HIGH_COMPLEXITY',
        regions: 'All India',
        contact_person: 'Sunita W',
        contact_phone: '+91-9845012367',
        contact_email: 'sunita@trustlegal.in',
        recovery_rate_overall: 0.72,
        avg_days_to_recovery: 44,
        total_cases_handled: 600,
        commission_rate: 0.34,
        min_case_amount: 50000,
        max_case_amount: 2000000,
        status: 'ACTIVE',
        performance_score: 7.8,
        sla_first_contact_hours: 24,
        sla_recovery_days: 60,
        created_date: '2025-03-10',
        last_performance_review: '2026-01-05',
        api_endpoint: 'https://trustlegal.in/api',
        api_auth_token: 'token_23',
        is_preferred_partner: 0,
        notes: '',
      },
      {
        dca_id: 'DCA-URBAN-39',
        agency_name: 'Urban Debt Mgmt',
        short_name: 'Urban DM',
        specialization: 'B2C_AVOIDANCE',
        regions: 'Urban Areas',
        contact_person: 'Harish Z',
        contact_phone: '+91-9845012383',
        contact_email: 'harish@urbandm.in',
        recovery_rate_overall: 0.61,
        avg_days_to_recovery: 28,
        total_cases_handled: 8000,
        commission_rate: 0.27,
        min_case_amount: 500,
        max_case_amount: 12000,
        status: 'ACTIVE',
        performance_score: 7.4,
        sla_first_contact_hours: 4,
        sla_recovery_days: 30,
        created_date: '2025-07-28',
        last_performance_review: '2026-01-03',
        api_endpoint: 'https://urbandm.in/api',
        api_auth_token: 'token_39',
        is_preferred_partner: 0,
        notes: '',
      },
      {
        dca_id: 'DCA-VALUE-22',
        agency_name: 'Value Added Collections',
        short_name: 'Value Col',
        specialization: 'ADMIN_FEES',
        regions: 'West_India',
        contact_person: 'Ramesh G',
        contact_phone: '+91-9845012366',
        contact_email: 'ramesh@valuecol.in',
        recovery_rate_overall: 0.63,
        avg_days_to_recovery: 21,
        total_cases_handled: 5500,
        commission_rate: 0.22,
        min_case_amount: 500,
        max_case_amount: 15000,
        status: 'WARNING',
        performance_score: 6.7,
        sla_first_contact_hours: 48,
        sla_recovery_days: 30,
        created_date: '2025-07-15',
        last_performance_review: '2026-01-01',
        api_endpoint: 'https://valuecol.in/api',
        api_auth_token: 'token_22',
        is_preferred_partner: 0,
        notes: '',
      },
      {
        dca_id: 'DCA-WEST-12',
        agency_name: 'Western Ghats Collections',
        short_name: 'West Col',
        specialization: 'FREIGHT_GENERAL',
        regions: 'West_India',
        contact_person: 'Sneha P',
        contact_phone: '+91-9845012356',
        contact_email: 'sneha@westcol.in',
        recovery_rate_overall: 0.81,
        avg_days_to_recovery: 24,
        total_cases_handled: 2200,
        commission_rate: 0.25,
        min_case_amount: 2000,
        max_case_amount: 150000,
        status: 'ACTIVE',
        performance_score: 8.6,
        sla_first_contact_hours: 24,
        sla_recovery_days: 40,
        created_date: '2025-06-10',
        last_performance_review: '2026-01-03',
        api_endpoint: 'https://westcol.in/api',
        api_auth_token: 'token_12',
        is_preferred_partner: 0,
        notes: '',
      },
      {
        dca_id: 'DCA-ZENITH-50',
        agency_name: 'Zenith Recovery',
        short_name: 'Zenith Rec',
        specialization: 'ADMIN_FEES',
        regions: 'All India',
        contact_person: 'Alok G',
        contact_phone: '+91-9845012394',
        contact_email: 'alok@zenithrec.in',
        recovery_rate_overall: 0.62,
        avg_days_to_recovery: 21,
        total_cases_handled: 5200,
        commission_rate: 0.22,
        min_case_amount: 500,
        max_case_amount: 15000,
        status: 'WARNING',
        performance_score: 6.8,
        sla_first_contact_hours: 48,
        sla_recovery_days: 30,
        created_date: '2025-04-22',
        last_performance_review: '2026-01-01',
        api_endpoint: 'https://zenithrec.in/api',
        api_auth_token: 'token_50',
        is_preferred_partner: 0,
        notes: '',
      },
      {
        dca_id: 'DCA-ZONE-37',
        agency_name: 'Zone 1 Recovery',
        short_name: 'Zone 1',
        specialization: 'CUSTOMS_DISPUTE',
        regions: 'North_India',
        contact_person: 'Rakesh Q',
        contact_phone: '+91-9845012381',
        contact_email: 'rakesh@zone1.in',
        recovery_rate_overall: 0.73,
        avg_days_to_recovery: 31,
        total_cases_handled: 1400,
        commission_rate: 0.28,
        min_case_amount: 5000,
        max_case_amount: 200000,
        status: 'ACTIVE',
        performance_score: 7.8,
        sla_first_contact_hours: 24,
        sla_recovery_days: 45,
        created_date: '2025-05-18',
        last_performance_review: '2026-01-05',
        api_endpoint: 'https://zone1.in/api',
        api_auth_token: 'token_37',
        is_preferred_partner: 0,
        notes: '',
      },
    ]);

    // case Summary

    const caseSummaries = await DcaCasesSummary.bulkCreate([
      {
        id: 1,
        dca_id: 'DCA-CUSTIND-01',
        month_year: '2026-01',
        total_cases_assigned: 45,
        cases_recovered: 35,
        recovered_amount: 285000,
        avg_recovery_days: 28,
        sla_breaches: 2,
        performance_trend: 'IMPROVING',
      },
      {
        id: 2,
        dca_id: 'DCA-FRTGEN-02',
        month_year: '2026-01',
        total_cases_assigned: 120,
        cases_recovered: 98,
        recovered_amount: 85000,
        avg_recovery_days: 22,
        sla_breaches: 1,
        performance_trend: 'STABLE',
      },
      {
        id: 3,
        dca_id: 'DCA-SMALLCL-03',
        month_year: '2026-01',
        total_cases_assigned: 350,
        cases_recovered: 220,
        recovered_amount: 12000,
        avg_recovery_days: 18,
        sla_breaches: 15,
        performance_trend: 'DECLINING',
      },
      {
        id: 4,
        dca_id: 'DCA-LEGAL-04',
        month_year: '2026-01',
        total_cases_assigned: 12,
        cases_recovered: 8,
        recovered_amount: 450000,
        avg_recovery_days: 45,
        sla_breaches: 0,
        performance_trend: 'STABLE',
      },
      {
        id: 5,
        dca_id: 'DCA-B2BEXP-05',
        month_year: '2026-01',
        total_cases_assigned: 85,
        cases_recovered: 75,
        recovered_amount: 125000,
        avg_recovery_days: 25,
        sla_breaches: 0,
        performance_trend: 'IMPROVING',
      },
      {
        id: 6,
        dca_id: 'DCA-AVGRES-06',
        month_year: '2026-01',
        total_cases_assigned: 60,
        cases_recovered: 35,
        recovered_amount: 18000,
        avg_recovery_days: 35,
        sla_breaches: 5,
        performance_trend: 'DECLINING',
      },
      {
        id: 7,
        dca_id: 'DCA-SMSHUNT-07',
        month_year: '2026-01',
        total_cases_assigned: 400,
        cases_recovered: 230,
        recovered_amount: 10000,
        avg_recovery_days: 29,
        sla_breaches: 8,
        performance_trend: 'STABLE',
      },
      {
        id: 8,
        dca_id: 'DCA-FIELD-08',
        month_year: '2026-01',
        total_cases_assigned: 25,
        cases_recovered: 18,
        recovered_amount: 15000,
        avg_recovery_days: 38,
        sla_breaches: 2,
        performance_trend: 'STABLE',
      },
      {
        id: 9,
        dca_id: 'DCA-PENREC-09',
        month_year: '2026-01',
        total_cases_assigned: 15,
        cases_recovered: 8,
        recovered_amount: 5000,
        avg_recovery_days: 42,
        sla_breaches: 3,
        performance_trend: 'DECLINING',
      },
      {
        id: 10,
        dca_id: 'DCA-ENTERP-10',
        month_year: '2026-01',
        total_cases_assigned: 30,
        cases_recovered: 24,
        recovered_amount: 210000,
        avg_recovery_days: 33,
        sla_breaches: 1,
        performance_trend: 'IMPROVING',
      },
      {
        id: 11,
        dca_id: 'DCA-NORTH-11',
        month_year: '2026-01',
        total_cases_assigned: 40,
        cases_recovered: 30,
        recovered_amount: 65000,
        avg_recovery_days: 30,
        sla_breaches: 2,
        performance_trend: 'STABLE',
      },
      {
        id: 12,
        dca_id: 'DCA-WEST-12',
        month_year: '2026-01',
        total_cases_assigned: 65,
        cases_recovered: 53,
        recovered_amount: 48000,
        avg_recovery_days: 24,
        sla_breaches: 1,
        performance_trend: 'IMPROVING',
      },
      {
        id: 13,
        dca_id: 'DCA-EAST-13',
        month_year: '2026-01',
        total_cases_assigned: 35,
        cases_recovered: 22,
        recovered_amount: 22000,
        avg_recovery_days: 32,
        sla_breaches: 4,
        performance_trend: 'DECLINING',
      },
      {
        id: 14,
        dca_id: 'DCA-TECH-14',
        month_year: '2026-01',
        total_cases_assigned: 250,
        cases_recovered: 150,
        recovered_amount: 7500,
        avg_recovery_days: 20,
        sla_breaches: 6,
        performance_trend: 'STABLE',
      },
      {
        id: 15,
        dca_id: 'DCA-PREMIUM-15',
        month_year: '2026-01',
        total_cases_assigned: 20,
        cases_recovered: 17,
        recovered_amount: 180000,
        avg_recovery_days: 31,
        sla_breaches: 0,
        performance_trend: 'IMPROVING',
      },
      {
        id: 16,
        dca_id: 'DCA-RAPID-16',
        month_year: '2026-01',
        total_cases_assigned: 110,
        cases_recovered: 75,
        recovered_amount: 11000,
        avg_recovery_days: 19,
        sla_breaches: 3,
        performance_trend: 'STABLE',
      },
      {
        id: 17,
        dca_id: 'DCA-SECURE-17',
        month_year: '2026-01',
        total_cases_assigned: 50,
        cases_recovered: 38,
        recovered_amount: 72000,
        avg_recovery_days: 29,
        sla_breaches: 1,
        performance_trend: 'IMPROVING',
      },
      {
        id: 18,
        dca_id: 'DCA-GLOBAL-18',
        month_year: '2026-01',
        total_cases_assigned: 70,
        cases_recovered: 56,
        recovered_amount: 95000,
        avg_recovery_days: 27,
        sla_breaches: 2,
        performance_trend: 'STABLE',
      },
      {
        id: 19,
        dca_id: 'DCA-LOCAL-19',
        month_year: '2026-01',
        total_cases_assigned: 22,
        cases_recovered: 14,
        recovered_amount: 8000,
        avg_recovery_days: 41,
        sla_breaches: 3,
        performance_trend: 'STABLE',
      },
      {
        id: 20,
        dca_id: 'DCA-CORP-20',
        month_year: '2026-01',
        total_cases_assigned: 80,
        cases_recovered: 68,
        recovered_amount: 110000,
        avg_recovery_days: 26,
        sla_breaches: 0,
        performance_trend: 'IMPROVING',
      },
      {
        id: 21,
        dca_id: 'DCA-EXPRESS-21',
        month_year: '2026-01',
        total_cases_assigned: 95,
        cases_recovered: 73,
        recovered_amount: 55000,
        avg_recovery_days: 23,
        sla_breaches: 2,
        performance_trend: 'STABLE',
      },
      {
        id: 22,
        dca_id: 'DCA-VALUE-22',
        month_year: '2026-01',
        total_cases_assigned: 130,
        cases_recovered: 80,
        recovered_amount: 5000,
        avg_recovery_days: 21,
        sla_breaches: 10,
        performance_trend: 'DECLINING',
      },
      {
        id: 23,
        dca_id: 'DCA-TRUST-23',
        month_year: '2026-01',
        total_cases_assigned: 15,
        cases_recovered: 11,
        recovered_amount: 280000,
        avg_recovery_days: 44,
        sla_breaches: 1,
        performance_trend: 'STABLE',
      },
      {
        id: 24,
        dca_id: 'DCA-AGILE-24',
        month_year: '2026-01',
        total_cases_assigned: 55,
        cases_recovered: 48,
        recovered_amount: 85000,
        avg_recovery_days: 25,
        sla_breaches: 0,
        performance_trend: 'IMPROVING',
      },
      {
        id: 25,
        dca_id: 'DCA-CITY-25',
        month_year: '2026-01',
        total_cases_assigned: 220,
        cases_recovered: 130,
        recovered_amount: 9000,
        avg_recovery_days: 28,
        sla_breaches: 5,
        performance_trend: 'STABLE',
      },
      {
        id: 26,
        dca_id: 'DCA-RURAL-26',
        month_year: '2026-01',
        total_cases_assigned: 18,
        cases_recovered: 11,
        recovered_amount: 4000,
        avg_recovery_days: 40,
        sla_breaches: 1,
        performance_trend: 'STABLE',
      },
      {
        id: 27,
        dca_id: 'DCA-PRIORITY-27',
        month_year: '2026-01',
        total_cases_assigned: 38,
        cases_recovered: 29,
        recovered_amount: 58000,
        avg_recovery_days: 29,
        sla_breaches: 1,
        performance_trend: 'IMPROVING',
      },
      {
        id: 28,
        dca_id: 'DCA-LOGISTIC-28',
        month_year: '2026-01',
        total_cases_assigned: 75,
        cases_recovered: 60,
        recovered_amount: 52000,
        avg_recovery_days: 24,
        sla_breaches: 2,
        performance_trend: 'STABLE',
      },
      {
        id: 29,
        dca_id: 'DCA-MICRO-29',
        month_year: '2026-01',
        total_cases_assigned: 150,
        cases_recovered: 95,
        recovered_amount: 6500,
        avg_recovery_days: 20,
        sla_breaches: 8,
        performance_trend: 'DECLINING',
      },
      {
        id: 30,
        dca_id: 'DCA-PARTNER-30',
        month_year: '2026-01',
        total_cases_assigned: 28,
        cases_recovered: 23,
        recovered_amount: 195000,
        avg_recovery_days: 32,
        sla_breaches: 0,
        performance_trend: 'IMPROVING',
      },
      {
        id: 31,
        dca_id: 'DCA-FAST-31',
        month_year: '2026-01',
        total_cases_assigned: 62,
        cases_recovered: 48,
        recovered_amount: 78000,
        avg_recovery_days: 27,
        sla_breaches: 2,
        performance_trend: 'STABLE',
      },
      {
        id: 32,
        dca_id: 'DCA-NATION-32',
        month_year: '2026-01',
        total_cases_assigned: 105,
        cases_recovered: 85,
        recovered_amount: 75000,
        avg_recovery_days: 23,
        sla_breaches: 1,
        performance_trend: 'IMPROVING',
      },
      {
        id: 33,
        dca_id: 'DCA-RETAIL-33',
        month_year: '2026-01',
        total_cases_assigned: 280,
        cases_recovered: 160,
        recovered_amount: 10500,
        avg_recovery_days: 30,
        sla_breaches: 9,
        performance_trend: 'STABLE',
      },
      {
        id: 34,
        dca_id: 'DCA-HEAVY-34',
        month_year: '2026-01',
        total_cases_assigned: 45,
        cases_recovered: 38,
        recovered_amount: 92000,
        avg_recovery_days: 26,
        sla_breaches: 1,
        performance_trend: 'IMPROVING',
      },
      {
        id: 35,
        dca_id: 'DCA-DISPUTE-35',
        month_year: '2026-01',
        total_cases_assigned: 14,
        cases_recovered: 10,
        recovered_amount: 60000,
        avg_recovery_days: 43,
        sla_breaches: 2,
        performance_trend: 'STABLE',
      },
      {
        id: 36,
        dca_id: 'DCA-DIGITAL-36',
        month_year: '2026-01',
        total_cases_assigned: 180,
        cases_recovered: 120,
        recovered_amount: 7800,
        avg_recovery_days: 19,
        sla_breaches: 4,
        performance_trend: 'IMPROVING',
      },
      {
        id: 37,
        dca_id: 'DCA-ZONE-37',
        month_year: '2026-01',
        total_cases_assigned: 36,
        cases_recovered: 26,
        recovered_amount: 45000,
        avg_recovery_days: 31,
        sla_breaches: 2,
        performance_trend: 'STABLE',
      },
      {
        id: 38,
        dca_id: 'DCA-CARGO-38',
        month_year: '2026-01',
        total_cases_assigned: 30,
        cases_recovered: 20,
        recovered_amount: 16000,
        avg_recovery_days: 33,
        sla_breaches: 3,
        performance_trend: 'DECLINING',
      },
      {
        id: 39,
        dca_id: 'DCA-URBAN-39',
        month_year: '2026-01',
        total_cases_assigned: 210,
        cases_recovered: 125,
        recovered_amount: 8200,
        avg_recovery_days: 28,
        sla_breaches: 6,
        performance_trend: 'STABLE',
      },
      {
        id: 40,
        dca_id: 'DCA-PRIME-40',
        month_year: '2026-01',
        total_cases_assigned: 25,
        cases_recovered: 20,
        recovered_amount: 165000,
        avg_recovery_days: 32,
        sla_breaches: 0,
        performance_trend: 'IMPROVING',
      },
      {
        id: 41,
        dca_id: 'DCA-LINK-41',
        month_year: '2026-01',
        total_cases_assigned: 68,
        cases_recovered: 53,
        recovered_amount: 42000,
        avg_recovery_days: 22,
        sla_breaches: 1,
        performance_trend: 'STABLE',
      },
      {
        id: 42,
        dca_id: 'DCA-TASK-42',
        month_year: '2026-01',
        total_cases_assigned: 20,
        cases_recovered: 14,
        recovered_amount: 6000,
        avg_recovery_days: 39,
        sla_breaches: 1,
        performance_trend: 'STABLE',
      },
      {
        id: 43,
        dca_id: 'DCA-CORE-43',
        month_year: '2026-01',
        total_cases_assigned: 48,
        cases_recovered: 41,
        recovered_amount: 70000,
        avg_recovery_days: 25,
        sla_breaches: 0,
        performance_trend: 'IMPROVING',
      },
      {
        id: 44,
        dca_id: 'DCA-SWIFT-44',
        month_year: '2026-01',
        total_cases_assigned: 12,
        cases_recovered: 6,
        recovered_amount: 3500,
        avg_recovery_days: 41,
        sla_breaches: 2,
        performance_trend: 'DECLINING',
      },
      {
        id: 45,
        dca_id: 'DCA-METRO-45',
        month_year: '2026-01',
        total_cases_assigned: 115,
        cases_recovered: 78,
        recovered_amount: 5800,
        avg_recovery_days: 18,
        sla_breaches: 3,
        performance_trend: 'STABLE',
      },
      {
        id: 46,
        dca_id: 'DCA-ELITE-46',
        month_year: '2026-01',
        total_cases_assigned: 10,
        cases_recovered: 7,
        recovered_amount: 220000,
        avg_recovery_days: 46,
        sla_breaches: 0,
        performance_trend: 'STABLE',
      },
      {
        id: 47,
        dca_id: 'DCA-OMEGA-47',
        month_year: '2026-01',
        total_cases_assigned: 32,
        cases_recovered: 25,
        recovered_amount: 41000,
        avg_recovery_days: 28,
        sla_breaches: 1,
        performance_trend: 'IMPROVING',
      },
      {
        id: 48,
        dca_id: 'DCA-DELTA-48',
        month_year: '2026-01',
        total_cases_assigned: 72,
        cases_recovered: 59,
        recovered_amount: 54000,
        avg_recovery_days: 23,
        sla_breaches: 1,
        performance_trend: 'IMPROVING',
      },
      {
        id: 49,
        dca_id: 'DCA-SIGMA-49',
        month_year: '2026-01',
        total_cases_assigned: 26,
        cases_recovered: 22,
        recovered_amount: 32000,
        avg_recovery_days: 27,
        sla_breaches: 0,
        performance_trend: 'IMPROVING',
      },
      {
        id: 50,
        dca_id: 'DCA-ZENITH-50',
        month_year: '2026-01',
        total_cases_assigned: 140,
        cases_recovered: 88,
        recovered_amount: 6200,
        avg_recovery_days: 21,
        sla_breaches: 7,
        performance_trend: 'DECLINING',
      },
    ]);

    // dca Performance per Type
    const dcaPerformanceByType = await DcaPerformanceByType.bulkCreate([
      {
        id: 1,
        dca_id: 'DCA-CUSTIND-01',
        debt_category: 'CUSTOMS_DUTY',
        debtor_type: 'B2B',
        debt_cause: 'DISPUTE',
        cases_handled: 156,
        recovered_amount: 125600,
        recovery_rate: 0.82,
        avg_days_to_recovery: 32,
        avg_complexity_score: 7.2,
        cost_per_recovery: 0.25,
        sla_compliance_rate: 0.94,
        last_updated: '2026-01-07',
      },
      {
        id: 2,
        dca_id: 'DCA-FRTGEN-02',
        debt_category: 'FREIGHT',
        debtor_type: 'B2B',
        debt_cause: 'CASH_FLOW',
        cases_handled: 450,
        recovered_amount: 310000,
        recovery_rate: 0.85,
        avg_days_to_recovery: 24,
        avg_complexity_score: 5.5,
        cost_per_recovery: 0.22,
        sla_compliance_rate: 0.96,
        last_updated: '2026-01-07',
      },
      {
        id: 3,
        dca_id: 'DCA-SMALLCL-03',
        debt_category: 'ADMIN_FEES',
        debtor_type: 'B2C',
        debt_cause: 'AVOIDANCE',
        cases_handled: 1200,
        recovered_amount: 45000,
        recovery_rate: 0.6,
        avg_days_to_recovery: 20,
        avg_complexity_score: 3.1,
        cost_per_recovery: 0.18,
        sla_compliance_rate: 0.88,
        last_updated: '2026-01-07',
      },
      {
        id: 4,
        dca_id: 'DCA-LEGAL-04',
        debt_category: 'CUSTOMS_DUTY',
        debtor_type: 'B2B',
        debt_cause: 'DISPUTE',
        cases_handled: 45,
        recovered_amount: 850000,
        recovery_rate: 0.7,
        avg_days_to_recovery: 50,
        avg_complexity_score: 9.1,
        cost_per_recovery: 0.32,
        sla_compliance_rate: 0.92,
        last_updated: '2026-01-07',
      },
      {
        id: 5,
        dca_id: 'DCA-B2BEXP-05',
        debt_category: 'FREIGHT',
        debtor_type: 'B2B',
        debt_cause: 'CASH_FLOW',
        cases_handled: 310,
        recovered_amount: 550000,
        recovery_rate: 0.88,
        avg_days_to_recovery: 26,
        avg_complexity_score: 6.2,
        cost_per_recovery: 0.24,
        sla_compliance_rate: 0.98,
        last_updated: '2026-01-07',
      },
      {
        id: 6,
        dca_id: 'DCA-AVGRES-06',
        debt_category: 'FREIGHT',
        debtor_type: 'B2C',
        debt_cause: 'CASH_FLOW',
        cases_handled: 200,
        recovered_amount: 60000,
        recovery_rate: 0.65,
        avg_days_to_recovery: 38,
        avg_complexity_score: 4.5,
        cost_per_recovery: 0.2,
        sla_compliance_rate: 0.85,
        last_updated: '2026-01-07',
      },
      {
        id: 7,
        dca_id: 'DCA-SMSHUNT-07',
        debt_category: 'ADMIN_FEES',
        debtor_type: 'B2C',
        debt_cause: 'AVOIDANCE',
        cases_handled: 1500,
        recovered_amount: 35000,
        recovery_rate: 0.55,
        avg_days_to_recovery: 30,
        avg_complexity_score: 2.8,
        cost_per_recovery: 0.15,
        sla_compliance_rate: 0.9,
        last_updated: '2026-01-07',
      },
      {
        id: 8,
        dca_id: 'DCA-FIELD-08',
        debt_category: 'FREIGHT',
        debtor_type: 'B2C',
        debt_cause: 'AVOIDANCE',
        cases_handled: 85,
        recovered_amount: 42000,
        recovery_rate: 0.72,
        avg_days_to_recovery: 40,
        avg_complexity_score: 6.5,
        cost_per_recovery: 0.28,
        sla_compliance_rate: 0.89,
        last_updated: '2026-01-07',
      },
      {
        id: 9,
        dca_id: 'DCA-PENREC-09',
        debt_category: 'PENALTIES',
        debtor_type: 'B2B',
        debt_cause: 'DISPUTE',
        cases_handled: 60,
        recovered_amount: 25000,
        recovery_rate: 0.52,
        avg_days_to_recovery: 45,
        avg_complexity_score: 7.8,
        cost_per_recovery: 0.29,
        sla_compliance_rate: 0.8,
        last_updated: '2026-01-07',
      },
      {
        id: 10,
        dca_id: 'DCA-ENTERP-10',
        debt_category: 'FREIGHT',
        debtor_type: 'B2B',
        debt_cause: 'CASH_FLOW',
        cases_handled: 120,
        recovered_amount: 950000,
        recovery_rate: 0.81,
        avg_days_to_recovery: 35,
        avg_complexity_score: 8.2,
        cost_per_recovery: 0.27,
        sla_compliance_rate: 0.95,
        last_updated: '2026-01-07',
      },
      {
        id: 11,
        dca_id: 'DCA-NORTH-11',
        debt_category: 'CUSTOMS_DUTY',
        debtor_type: 'B2B',
        debt_cause: 'DISPUTE',
        cases_handled: 140,
        recovered_amount: 110000,
        recovery_rate: 0.76,
        avg_days_to_recovery: 31,
        avg_complexity_score: 7,
        cost_per_recovery: 0.26,
        sla_compliance_rate: 0.93,
        last_updated: '2026-01-07',
      },
      {
        id: 12,
        dca_id: 'DCA-WEST-12',
        debt_category: 'FREIGHT',
        debtor_type: 'B2B',
        debt_cause: 'CASH_FLOW',
        cases_handled: 220,
        recovered_amount: 180000,
        recovery_rate: 0.83,
        avg_days_to_recovery: 25,
        avg_complexity_score: 5.8,
        cost_per_recovery: 0.23,
        sla_compliance_rate: 0.95,
        last_updated: '2026-01-07',
      },
      {
        id: 13,
        dca_id: 'DCA-EAST-13',
        debt_category: 'FREIGHT',
        debtor_type: 'B2B',
        debt_cause: 'CASH_FLOW',
        cases_handled: 110,
        recovered_amount: 75000,
        recovery_rate: 0.68,
        avg_days_to_recovery: 34,
        avg_complexity_score: 5.6,
        cost_per_recovery: 0.24,
        sla_compliance_rate: 0.87,
        last_updated: '2026-01-07',
      },
      {
        id: 14,
        dca_id: 'DCA-TECH-14',
        debt_category: 'ADMIN_FEES',
        debtor_type: 'B2C',
        debt_cause: 'AVOIDANCE',
        cases_handled: 900,
        recovered_amount: 25000,
        recovery_rate: 0.58,
        avg_days_to_recovery: 22,
        avg_complexity_score: 3,
        cost_per_recovery: 0.19,
        sla_compliance_rate: 0.91,
        last_updated: '2026-01-07',
      },
      {
        id: 15,
        dca_id: 'DCA-PREMIUM-15',
        debt_category: 'FREIGHT',
        debtor_type: 'B2B',
        debt_cause: 'CASH_FLOW',
        cases_handled: 75,
        recovered_amount: 420000,
        recovery_rate: 0.85,
        avg_days_to_recovery: 33,
        avg_complexity_score: 8,
        cost_per_recovery: 0.28,
        sla_compliance_rate: 0.97,
        last_updated: '2026-01-07',
      },
      {
        id: 16,
        dca_id: 'DCA-RAPID-16',
        debt_category: 'ADMIN_FEES',
        debtor_type: 'B2B',
        debt_cause: 'CASH_FLOW',
        cases_handled: 350,
        recovered_amount: 48000,
        recovery_rate: 0.72,
        avg_days_to_recovery: 21,
        avg_complexity_score: 4,
        cost_per_recovery: 0.21,
        sla_compliance_rate: 0.94,
        last_updated: '2026-01-07',
      },
      {
        id: 17,
        dca_id: 'DCA-SECURE-17',
        debt_category: 'CUSTOMS_DUTY',
        debtor_type: 'B2B',
        debt_cause: 'DISPUTE',
        cases_handled: 180,
        recovered_amount: 145000,
        recovery_rate: 0.79,
        avg_days_to_recovery: 30,
        avg_complexity_score: 6.8,
        cost_per_recovery: 0.25,
        sla_compliance_rate: 0.93,
        last_updated: '2026-01-07',
      },
      {
        id: 18,
        dca_id: 'DCA-GLOBAL-18',
        debt_category: 'CUSTOMS_DUTY',
        debtor_type: 'B2B',
        debt_cause: 'DISPUTE',
        cases_handled: 250,
        recovered_amount: 320000,
        recovery_rate: 0.83,
        avg_days_to_recovery: 28,
        avg_complexity_score: 7.5,
        cost_per_recovery: 0.26,
        sla_compliance_rate: 0.96,
        last_updated: '2026-01-07',
      },
      {
        id: 19,
        dca_id: 'DCA-LOCAL-19',
        debt_category: 'FREIGHT',
        debtor_type: 'B2C',
        debt_cause: 'AVOIDANCE',
        cases_handled: 65,
        recovered_amount: 30000,
        recovery_rate: 0.64,
        avg_days_to_recovery: 42,
        avg_complexity_score: 6,
        cost_per_recovery: 0.29,
        sla_compliance_rate: 0.88,
        last_updated: '2026-01-07',
      },
      {
        id: 20,
        dca_id: 'DCA-CORP-20',
        debt_category: 'FREIGHT',
        debtor_type: 'B2B',
        debt_cause: 'CASH_FLOW',
        cases_handled: 280,
        recovered_amount: 380000,
        recovery_rate: 0.86,
        avg_days_to_recovery: 27,
        avg_complexity_score: 6.5,
        cost_per_recovery: 0.24,
        sla_compliance_rate: 0.98,
        last_updated: '2026-01-07',
      },
      {
        id: 21,
        dca_id: 'DCA-EXPRESS-21',
        debt_category: 'FREIGHT',
        debtor_type: 'B2B',
        debt_cause: 'CASH_FLOW',
        cases_handled: 320,
        recovered_amount: 210000,
        recovery_rate: 0.79,
        avg_days_to_recovery: 24,
        avg_complexity_score: 5.2,
        cost_per_recovery: 0.23,
        sla_compliance_rate: 0.94,
        last_updated: '2026-01-07',
      },
      {
        id: 22,
        dca_id: 'DCA-VALUE-22',
        debt_category: 'ADMIN_FEES',
        debtor_type: 'B2C',
        debt_cause: 'AVOIDANCE',
        cases_handled: 450,
        recovered_amount: 18000,
        recovery_rate: 0.62,
        avg_days_to_recovery: 23,
        avg_complexity_score: 3.2,
        cost_per_recovery: 0.2,
        sla_compliance_rate: 0.86,
        last_updated: '2026-01-07',
      },
      {
        id: 23,
        dca_id: 'DCA-TRUST-23',
        debt_category: 'CUSTOMS_DUTY',
        debtor_type: 'B2B',
        debt_cause: 'DISPUTE',
        cases_handled: 50,
        recovered_amount: 650000,
        recovery_rate: 0.74,
        avg_days_to_recovery: 48,
        avg_complexity_score: 8.8,
        cost_per_recovery: 0.31,
        sla_compliance_rate: 0.93,
        last_updated: '2026-01-07',
      },
      {
        id: 24,
        dca_id: 'DCA-AGILE-24',
        debt_category: 'FREIGHT',
        debtor_type: 'B2B',
        debt_cause: 'CASH_FLOW',
        cases_handled: 190,
        recovered_amount: 250000,
        recovery_rate: 0.89,
        avg_days_to_recovery: 26,
        avg_complexity_score: 6,
        cost_per_recovery: 0.25,
        sla_compliance_rate: 0.99,
        last_updated: '2026-01-07',
      },
      {
        id: 25,
        dca_id: 'DCA-CITY-25',
        debt_category: 'ADMIN_FEES',
        debtor_type: 'B2C',
        debt_cause: 'AVOIDANCE',
        cases_handled: 800,
        recovered_amount: 32000,
        recovery_rate: 0.56,
        avg_days_to_recovery: 29,
        avg_complexity_score: 2.9,
        cost_per_recovery: 0.18,
        sla_compliance_rate: 0.89,
        last_updated: '2026-01-07',
      },
      {
        id: 26,
        dca_id: 'DCA-RURAL-26',
        debt_category: 'FREIGHT',
        debtor_type: 'B2C',
        debt_cause: 'AVOIDANCE',
        cases_handled: 40,
        recovered_amount: 15000,
        recovery_rate: 0.6,
        avg_days_to_recovery: 41,
        avg_complexity_score: 6.2,
        cost_per_recovery: 0.3,
        sla_compliance_rate: 0.85,
        last_updated: '2026-01-07',
      },
      {
        id: 27,
        dca_id: 'DCA-PRIORITY-27',
        debt_category: 'CUSTOMS_DUTY',
        debtor_type: 'B2B',
        debt_cause: 'DISPUTE',
        cases_handled: 130,
        recovered_amount: 105000,
        recovery_rate: 0.77,
        avg_days_to_recovery: 30,
        avg_complexity_score: 7.1,
        cost_per_recovery: 0.26,
        sla_compliance_rate: 0.94,
        last_updated: '2026-01-07',
      },
      {
        id: 28,
        dca_id: 'DCA-LOGISTIC-28',
        debt_category: 'FREIGHT',
        debtor_type: 'B2B',
        debt_cause: 'CASH_FLOW',
        cases_handled: 260,
        recovered_amount: 190000,
        recovery_rate: 0.81,
        avg_days_to_recovery: 25,
        avg_complexity_score: 5.7,
        cost_per_recovery: 0.24,
        sla_compliance_rate: 0.95,
        last_updated: '2026-01-07',
      },
      {
        id: 29,
        dca_id: 'DCA-MICRO-29',
        debt_category: 'ADMIN_FEES',
        debtor_type: 'B2C',
        debt_cause: 'CASH_FLOW',
        cases_handled: 500,
        recovered_amount: 22000,
        recovery_rate: 0.63,
        avg_days_to_recovery: 22,
        avg_complexity_score: 3.5,
        cost_per_recovery: 0.21,
        sla_compliance_rate: 0.88,
        last_updated: '2026-01-07',
      },
      {
        id: 30,
        dca_id: 'DCA-PARTNER-30',
        debt_category: 'FREIGHT',
        debtor_type: 'B2B',
        debt_cause: 'CASH_FLOW',
        cases_handled: 95,
        recovered_amount: 550000,
        recovery_rate: 0.84,
        avg_days_to_recovery: 34,
        avg_complexity_score: 7.9,
        cost_per_recovery: 0.28,
        sla_compliance_rate: 0.96,
        last_updated: '2026-01-07',
      },
      {
        id: 31,
        dca_id: 'DCA-FAST-31',
        debt_category: 'CUSTOMS_DUTY',
        debtor_type: 'B2B',
        debt_cause: 'DISPUTE',
        cases_handled: 210,
        recovered_amount: 160000,
        recovery_rate: 0.78,
        avg_days_to_recovery: 28,
        avg_complexity_score: 7.3,
        cost_per_recovery: 0.26,
        sla_compliance_rate: 0.95,
        last_updated: '2026-01-07',
      },
      {
        id: 32,
        dca_id: 'DCA-NATION-32',
        debt_category: 'FREIGHT',
        debtor_type: 'B2B',
        debt_cause: 'CASH_FLOW',
        cases_handled: 380,
        recovered_amount: 290000,
        recovery_rate: 0.82,
        avg_days_to_recovery: 24,
        avg_complexity_score: 5.4,
        cost_per_recovery: 0.23,
        sla_compliance_rate: 0.96,
        last_updated: '2026-01-07',
      },
      {
        id: 33,
        dca_id: 'DCA-RETAIL-33',
        debt_category: 'ADMIN_FEES',
        debtor_type: 'B2C',
        debt_cause: 'AVOIDANCE',
        cases_handled: 1100,
        recovered_amount: 40000,
        recovery_rate: 0.55,
        avg_days_to_recovery: 31,
        avg_complexity_score: 3,
        cost_per_recovery: 0.17,
        sla_compliance_rate: 0.87,
        last_updated: '2026-01-07',
      },
      {
        id: 34,
        dca_id: 'DCA-HEAVY-34',
        debt_category: 'FREIGHT',
        debtor_type: 'B2B',
        debt_cause: 'CASH_FLOW',
        cases_handled: 150,
        recovered_amount: 310000,
        recovery_rate: 0.85,
        avg_days_to_recovery: 27,
        avg_complexity_score: 6.4,
        cost_per_recovery: 0.25,
        sla_compliance_rate: 0.97,
        last_updated: '2026-01-07',
      },
      {
        id: 35,
        dca_id: 'DCA-DISPUTE-35',
        debt_category: 'PENALTIES',
        debtor_type: 'B2B',
        debt_cause: 'DISPUTE',
        cases_handled: 45,
        recovered_amount: 120000,
        recovery_rate: 0.71,
        avg_days_to_recovery: 46,
        avg_complexity_score: 8.5,
        cost_per_recovery: 0.33,
        sla_compliance_rate: 0.92,
        last_updated: '2026-01-07',
      },
      {
        id: 36,
        dca_id: 'DCA-DIGITAL-36',
        debt_category: 'ADMIN_FEES',
        debtor_type: 'B2C',
        debt_cause: 'AVOIDANCE',
        cases_handled: 600,
        recovered_amount: 26000,
        recovery_rate: 0.65,
        avg_days_to_recovery: 20,
        avg_complexity_score: 3.3,
        cost_per_recovery: 0.2,
        sla_compliance_rate: 0.9,
        last_updated: '2026-01-07',
      },
      {
        id: 37,
        dca_id: 'DCA-ZONE-37',
        debt_category: 'CUSTOMS_DUTY',
        debtor_type: 'B2B',
        debt_cause: 'DISPUTE',
        cases_handled: 125,
        recovered_amount: 95000,
        recovery_rate: 0.75,
        avg_days_to_recovery: 32,
        avg_complexity_score: 6.9,
        cost_per_recovery: 0.27,
        sla_compliance_rate: 0.93,
        last_updated: '2026-01-07',
      },
      {
        id: 38,
        dca_id: 'DCA-CARGO-38',
        debt_category: 'FREIGHT',
        debtor_type: 'B2B',
        debt_cause: 'CASH_FLOW',
        cases_handled: 100,
        recovered_amount: 60000,
        recovery_rate: 0.69,
        avg_days_to_recovery: 35,
        avg_complexity_score: 5.9,
        cost_per_recovery: 0.25,
        sla_compliance_rate: 0.86,
        last_updated: '2026-01-07',
      },
      {
        id: 39,
        dca_id: 'DCA-URBAN-39',
        debt_category: 'ADMIN_FEES',
        debtor_type: 'B2C',
        debt_cause: 'AVOIDANCE',
        cases_handled: 750,
        recovered_amount: 28000,
        recovery_rate: 0.59,
        avg_days_to_recovery: 29,
        avg_complexity_score: 2.7,
        cost_per_recovery: 0.19,
        sla_compliance_rate: 0.89,
        last_updated: '2026-01-07',
      },
      {
        id: 40,
        dca_id: 'DCA-PRIME-40',
        debt_category: 'FREIGHT',
        debtor_type: 'B2B',
        debt_cause: 'CASH_FLOW',
        cases_handled: 85,
        recovered_amount: 480000,
        recovery_rate: 0.83,
        avg_days_to_recovery: 33,
        avg_complexity_score: 8.1,
        cost_per_recovery: 0.28,
        sla_compliance_rate: 0.96,
        last_updated: '2026-01-07',
      },
      {
        id: 41,
        dca_id: 'DCA-LINK-41',
        debt_category: 'FREIGHT',
        debtor_type: 'B2B',
        debt_cause: 'CASH_FLOW',
        cases_handled: 240,
        recovered_amount: 160000,
        recovery_rate: 0.8,
        avg_days_to_recovery: 23,
        avg_complexity_score: 5.3,
        cost_per_recovery: 0.24,
        sla_compliance_rate: 0.94,
        last_updated: '2026-01-07',
      },
      {
        id: 42,
        dca_id: 'DCA-TASK-42',
        debt_category: 'FREIGHT',
        debtor_type: 'B2C',
        debt_cause: 'AVOIDANCE',
        cases_handled: 55,
        recovered_amount: 20000,
        recovery_rate: 0.68,
        avg_days_to_recovery: 40,
        avg_complexity_score: 6.1,
        cost_per_recovery: 0.29,
        sla_compliance_rate: 0.88,
        last_updated: '2026-01-07',
      },
      {
        id: 43,
        dca_id: 'DCA-CORE-43',
        debt_category: 'FREIGHT',
        debtor_type: 'B2B',
        debt_cause: 'CASH_FLOW',
        cases_handled: 170,
        recovered_amount: 220000,
        recovery_rate: 0.87,
        avg_days_to_recovery: 26,
        avg_complexity_score: 6.3,
        cost_per_recovery: 0.25,
        sla_compliance_rate: 0.98,
        last_updated: '2026-01-07',
      },
      {
        id: 44,
        dca_id: 'DCA-SWIFT-44',
        debt_category: 'PENALTIES',
        debtor_type: 'B2B',
        debt_cause: 'DISPUTE',
        cases_handled: 35,
        recovered_amount: 18000,
        recovery_rate: 0.54,
        avg_days_to_recovery: 43,
        avg_complexity_score: 7.6,
        cost_per_recovery: 0.29,
        sla_compliance_rate: 0.82,
        last_updated: '2026-01-07',
      },
      {
        id: 45,
        dca_id: 'DCA-METRO-45',
        debt_category: 'ADMIN_FEES',
        debtor_type: 'B2B',
        debt_cause: 'CASH_FLOW',
        cases_handled: 400,
        recovered_amount: 24000,
        recovery_rate: 0.66,
        avg_days_to_recovery: 19,
        avg_complexity_score: 3.8,
        cost_per_recovery: 0.21,
        sla_compliance_rate: 0.91,
        last_updated: '2026-01-07',
      },
      {
        id: 46,
        dca_id: 'DCA-ELITE-46',
        debt_category: 'CUSTOMS_DUTY',
        debtor_type: 'B2B',
        debt_cause: 'DISPUTE',
        cases_handled: 30,
        recovered_amount: 450000,
        recovery_rate: 0.73,
        avg_days_to_recovery: 49,
        avg_complexity_score: 9,
        cost_per_recovery: 0.34,
        sla_compliance_rate: 0.93,
        last_updated: '2026-01-07',
      },
      {
        id: 47,
        dca_id: 'DCA-OMEGA-47',
        debt_category: 'CUSTOMS_DUTY',
        debtor_type: 'B2B',
        debt_cause: 'DISPUTE',
        cases_handled: 110,
        recovered_amount: 90000,
        recovery_rate: 0.78,
        avg_days_to_recovery: 29,
        avg_complexity_score: 7.1,
        cost_per_recovery: 0.27,
        sla_compliance_rate: 0.94,
        last_updated: '2026-01-07',
      },
      {
        id: 48,
        dca_id: 'DCA-DELTA-48',
        debt_category: 'FREIGHT',
        debtor_type: 'B2B',
        debt_cause: 'CASH_FLOW',
        cases_handled: 230,
        recovered_amount: 175000,
        recovery_rate: 0.83,
        avg_days_to_recovery: 24,
        avg_complexity_score: 5.5,
        cost_per_recovery: 0.24,
        sla_compliance_rate: 0.96,
        last_updated: '2026-01-07',
      },
      {
        id: 49,
        dca_id: 'DCA-SIGMA-49',
        debt_category: 'FREIGHT',
        debtor_type: 'B2B',
        debt_cause: 'CASH_FLOW',
        cases_handled: 80,
        recovered_amount: 70000,
        recovery_rate: 0.84,
        avg_days_to_recovery: 28,
        avg_complexity_score: 6.4,
        cost_per_recovery: 0.25,
        sla_compliance_rate: 0.97,
        last_updated: '2026-01-07',
      },
      {
        id: 50,
        dca_id: 'DCA-ZENITH-50',
        debt_category: 'ADMIN_FEES',
        debtor_type: 'B2C',
        debt_cause: 'AVOIDANCE',
        cases_handled: 480,
        recovered_amount: 19000,
        recovery_rate: 0.61,
        avg_days_to_recovery: 22,
        avg_complexity_score: 3.4,
        cost_per_recovery: 0.21,
        sla_compliance_rate: 0.87,
        last_updated: '2026-01-07',
      },
    ]);

    // dcasla Compliance

    const dcaSLACompliance = await DcaSlaCompliance.bulkCreate([
      {
        id: 1,
        dca_id: 'DCA-CUSTIND-01',
        sla_type: 'FIRST_CONTACT_24H',
        target_hours: 24,
        compliance_rate: 0.94,
        total_checks: 156,
        breach_count: 9,
        last_breach_date: '2026-01-03',
      },
      {
        id: 2,
        dca_id: 'DCA-FRTGEN-02',
        sla_type: 'FIRST_CONTACT_24H',
        target_hours: 24,
        compliance_rate: 0.98,
        total_checks: 450,
        breach_count: 9,
        last_breach_date: '2025-12-28',
      },
      {
        id: 3,
        dca_id: 'DCA-SMALLCL-03',
        sla_type: 'FIRST_CONTACT_24H',
        target_hours: 48,
        compliance_rate: 0.85,
        total_checks: 1200,
        breach_count: 180,
        last_breach_date: '2026-01-05',
      },
      {
        id: 4,
        dca_id: 'DCA-LEGAL-04',
        sla_type: 'FIRST_CONTACT_24H',
        target_hours: 24,
        compliance_rate: 0.96,
        total_checks: 45,
        breach_count: 2,
        last_breach_date: '2025-11-15',
      },
      {
        id: 5,
        dca_id: 'DCA-B2BEXP-05',
        sla_type: 'FIRST_CONTACT_24H',
        target_hours: 12,
        compliance_rate: 0.99,
        total_checks: 310,
        breach_count: 3,
        last_breach_date: '2025-12-10',
      },
      {
        id: 6,
        dca_id: 'DCA-AVGRES-06',
        sla_type: 'FIRST_CONTACT_24H',
        target_hours: 36,
        compliance_rate: 0.82,
        total_checks: 200,
        breach_count: 36,
        last_breach_date: '2026-01-02',
      },
      {
        id: 7,
        dca_id: 'DCA-SMSHUNT-07',
        sla_type: 'FIRST_CONTACT_24H',
        target_hours: 4,
        compliance_rate: 0.92,
        total_checks: 1500,
        breach_count: 120,
        last_breach_date: '2026-01-06',
      },
      {
        id: 8,
        dca_id: 'DCA-FIELD-08',
        sla_type: 'FIRST_CONTACT_24H',
        target_hours: 48,
        compliance_rate: 0.88,
        total_checks: 85,
        breach_count: 10,
        last_breach_date: '2025-12-20',
      },
      {
        id: 9,
        dca_id: 'DCA-PENREC-09',
        sla_type: 'FIRST_CONTACT_24H',
        target_hours: 24,
        compliance_rate: 0.75,
        total_checks: 60,
        breach_count: 15,
        last_breach_date: '2026-01-04',
      },
      {
        id: 10,
        dca_id: 'DCA-ENTERP-10',
        sla_type: 'FIRST_CONTACT_24H',
        target_hours: 12,
        compliance_rate: 0.97,
        total_checks: 120,
        breach_count: 4,
        last_breach_date: '2025-12-30',
      },
      {
        id: 11,
        dca_id: 'DCA-NORTH-11',
        sla_type: 'FIRST_CONTACT_24H',
        target_hours: 24,
        compliance_rate: 0.95,
        total_checks: 140,
        breach_count: 7,
        last_breach_date: '2026-01-01',
      },
      {
        id: 12,
        dca_id: 'DCA-WEST-12',
        sla_type: 'FIRST_CONTACT_24H',
        target_hours: 24,
        compliance_rate: 0.96,
        total_checks: 220,
        breach_count: 9,
        last_breach_date: '2025-12-25',
      },
      {
        id: 13,
        dca_id: 'DCA-EAST-13',
        sla_type: 'FIRST_CONTACT_24H',
        target_hours: 36,
        compliance_rate: 0.84,
        total_checks: 110,
        breach_count: 18,
        last_breach_date: '2026-01-03',
      },
      {
        id: 14,
        dca_id: 'DCA-TECH-14',
        sla_type: 'FIRST_CONTACT_24H',
        target_hours: 4,
        compliance_rate: 0.93,
        total_checks: 900,
        breach_count: 63,
        last_breach_date: '2026-01-05',
      },
      {
        id: 15,
        dca_id: 'DCA-PREMIUM-15',
        sla_type: 'FIRST_CONTACT_24H',
        target_hours: 12,
        compliance_rate: 0.98,
        total_checks: 75,
        breach_count: 1,
        last_breach_date: '2025-11-20',
      },
      {
        id: 16,
        dca_id: 'DCA-RAPID-16',
        sla_type: 'FIRST_CONTACT_24H',
        target_hours: 24,
        compliance_rate: 0.94,
        total_checks: 350,
        breach_count: 21,
        last_breach_date: '2025-12-29',
      },
      {
        id: 17,
        dca_id: 'DCA-SECURE-17',
        sla_type: 'FIRST_CONTACT_24H',
        target_hours: 24,
        compliance_rate: 0.95,
        total_checks: 180,
        breach_count: 9,
        last_breach_date: '2026-01-02',
      },
      {
        id: 18,
        dca_id: 'DCA-GLOBAL-18',
        sla_type: 'FIRST_CONTACT_24H',
        target_hours: 24,
        compliance_rate: 0.97,
        total_checks: 250,
        breach_count: 7,
        last_breach_date: '2025-12-15',
      },
      {
        id: 19,
        dca_id: 'DCA-LOCAL-19',
        sla_type: 'FIRST_CONTACT_24H',
        target_hours: 48,
        compliance_rate: 0.86,
        total_checks: 65,
        breach_count: 9,
        last_breach_date: '2025-12-22',
      },
      {
        id: 20,
        dca_id: 'DCA-CORP-20',
        sla_type: 'FIRST_CONTACT_24H',
        target_hours: 24,
        compliance_rate: 0.99,
        total_checks: 280,
        breach_count: 3,
        last_breach_date: '2025-12-12',
      },
      {
        id: 21,
        dca_id: 'DCA-EXPRESS-21',
        sla_type: 'FIRST_CONTACT_24H',
        target_hours: 24,
        compliance_rate: 0.93,
        total_checks: 320,
        breach_count: 22,
        last_breach_date: '2026-01-01',
      },
      {
        id: 22,
        dca_id: 'DCA-VALUE-22',
        sla_type: 'FIRST_CONTACT_24H',
        target_hours: 48,
        compliance_rate: 0.83,
        total_checks: 450,
        breach_count: 76,
        last_breach_date: '2026-01-04',
      },
      {
        id: 23,
        dca_id: 'DCA-TRUST-23',
        sla_type: 'FIRST_CONTACT_24H',
        target_hours: 24,
        compliance_rate: 0.94,
        total_checks: 50,
        breach_count: 3,
        last_breach_date: '2025-11-25',
      },
      {
        id: 24,
        dca_id: 'DCA-AGILE-24',
        sla_type: 'FIRST_CONTACT_24H',
        target_hours: 12,
        compliance_rate: 1,
        total_checks: 190,
        breach_count: 0,
        last_breach_date: '',
      },
      {
        id: 25,
        dca_id: 'DCA-CITY-25',
        sla_type: 'FIRST_CONTACT_24H',
        target_hours: 4,
        compliance_rate: 0.91,
        total_checks: 800,
        breach_count: 72,
        last_breach_date: '2026-01-06',
      },
      {
        id: 26,
        dca_id: 'DCA-RURAL-26',
        sla_type: 'FIRST_CONTACT_24H',
        target_hours: 72,
        compliance_rate: 0.9,
        total_checks: 40,
        breach_count: 4,
        last_breach_date: '2025-12-18',
      },
      {
        id: 27,
        dca_id: 'DCA-PRIORITY-27',
        sla_type: 'FIRST_CONTACT_24H',
        target_hours: 24,
        compliance_rate: 0.95,
        total_checks: 130,
        breach_count: 6,
        last_breach_date: '2026-01-03',
      },
      {
        id: 28,
        dca_id: 'DCA-LOGISTIC-28',
        sla_type: 'FIRST_CONTACT_24H',
        target_hours: 24,
        compliance_rate: 0.96,
        total_checks: 260,
        breach_count: 10,
        last_breach_date: '2025-12-27',
      },
      {
        id: 29,
        dca_id: 'DCA-MICRO-29',
        sla_type: 'FIRST_CONTACT_24H',
        target_hours: 48,
        compliance_rate: 0.87,
        total_checks: 500,
        breach_count: 65,
        last_breach_date: '2026-01-02',
      },
      {
        id: 30,
        dca_id: 'DCA-PARTNER-30',
        sla_type: 'FIRST_CONTACT_24H',
        target_hours: 12,
        compliance_rate: 0.97,
        total_checks: 95,
        breach_count: 3,
        last_breach_date: '2025-12-28',
      },
      {
        id: 31,
        dca_id: 'DCA-FAST-31',
        sla_type: 'FIRST_CONTACT_24H',
        target_hours: 24,
        compliance_rate: 0.96,
        total_checks: 210,
        breach_count: 8,
        last_breach_date: '2026-01-01',
      },
      {
        id: 32,
        dca_id: 'DCA-NATION-32',
        sla_type: 'FIRST_CONTACT_24H',
        target_hours: 24,
        compliance_rate: 0.97,
        total_checks: 380,
        breach_count: 11,
        last_breach_date: '2025-12-26',
      },
      {
        id: 33,
        dca_id: 'DCA-RETAIL-33',
        sla_type: 'FIRST_CONTACT_24H',
        target_hours: 4,
        compliance_rate: 0.89,
        total_checks: 1100,
        breach_count: 121,
        last_breach_date: '2026-01-05',
      },
      {
        id: 34,
        dca_id: 'DCA-HEAVY-34',
        sla_type: 'FIRST_CONTACT_24H',
        target_hours: 12,
        compliance_rate: 0.98,
        total_checks: 150,
        breach_count: 3,
        last_breach_date: '2025-12-15',
      },
      {
        id: 35,
        dca_id: 'DCA-DISPUTE-35',
        sla_type: 'FIRST_CONTACT_24H',
        target_hours: 24,
        compliance_rate: 0.92,
        total_checks: 45,
        breach_count: 4,
        last_breach_date: '2025-11-30',
      },
      {
        id: 36,
        dca_id: 'DCA-DIGITAL-36',
        sla_type: 'FIRST_CONTACT_24H',
        target_hours: 48,
        compliance_rate: 0.9,
        total_checks: 600,
        breach_count: 60,
        last_breach_date: '2026-01-03',
      },
      {
        id: 37,
        dca_id: 'DCA-ZONE-37',
        sla_type: 'FIRST_CONTACT_24H',
        target_hours: 24,
        compliance_rate: 0.94,
        total_checks: 125,
        breach_count: 7,
        last_breach_date: '2026-01-02',
      },
      {
        id: 38,
        dca_id: 'DCA-CARGO-38',
        sla_type: 'FIRST_CONTACT_24H',
        target_hours: 36,
        compliance_rate: 0.85,
        total_checks: 100,
        breach_count: 15,
        last_breach_date: '2025-12-29',
      },
      {
        id: 39,
        dca_id: 'DCA-URBAN-39',
        sla_type: 'FIRST_CONTACT_24H',
        target_hours: 4,
        compliance_rate: 0.91,
        total_checks: 750,
        breach_count: 67,
        last_breach_date: '2026-01-04',
      },
      {
        id: 40,
        dca_id: 'DCA-PRIME-40',
        sla_type: 'FIRST_CONTACT_24H',
        target_hours: 12,
        compliance_rate: 0.97,
        total_checks: 85,
        breach_count: 2,
        last_breach_date: '2025-12-10',
      },
      {
        id: 41,
        dca_id: 'DCA-LINK-41',
        sla_type: 'FIRST_CONTACT_24H',
        target_hours: 24,
        compliance_rate: 0.93,
        total_checks: 240,
        breach_count: 17,
        last_breach_date: '2026-01-01',
      },
      {
        id: 42,
        dca_id: 'DCA-TASK-42',
        sla_type: 'FIRST_CONTACT_24H',
        target_hours: 48,
        compliance_rate: 0.89,
        total_checks: 55,
        breach_count: 6,
        last_breach_date: '2025-12-21',
      },
      {
        id: 43,
        dca_id: 'DCA-CORE-43',
        sla_type: 'FIRST_CONTACT_24H',
        target_hours: 12,
        compliance_rate: 0.99,
        total_checks: 170,
        breach_count: 2,
        last_breach_date: '2025-12-18',
      },
      {
        id: 44,
        dca_id: 'DCA-SWIFT-44',
        sla_type: 'FIRST_CONTACT_24H',
        target_hours: 24,
        compliance_rate: 0.78,
        total_checks: 35,
        breach_count: 8,
        last_breach_date: '2026-01-05',
      },
      {
        id: 45,
        dca_id: 'DCA-METRO-45',
        sla_type: 'FIRST_CONTACT_24H',
        target_hours: 48,
        compliance_rate: 0.91,
        total_checks: 400,
        breach_count: 36,
        last_breach_date: '2026-01-02',
      },
      {
        id: 46,
        dca_id: 'DCA-ELITE-46',
        sla_type: 'FIRST_CONTACT_24H',
        target_hours: 24,
        compliance_rate: 0.95,
        total_checks: 30,
        breach_count: 1,
        last_breach_date: '2025-11-28',
      },
      {
        id: 47,
        dca_id: 'DCA-OMEGA-47',
        sla_type: 'FIRST_CONTACT_24H',
        target_hours: 24,
        compliance_rate: 0.96,
        total_checks: 110,
        breach_count: 4,
        last_breach_date: '2026-01-03',
      },
      {
        id: 48,
        dca_id: 'DCA-DELTA-48',
        sla_type: 'FIRST_CONTACT_24H',
        target_hours: 24,
        compliance_rate: 0.97,
        total_checks: 230,
        breach_count: 7,
        last_breach_date: '2025-12-24',
      },
      {
        id: 49,
        dca_id: 'DCA-SIGMA-49',
        sla_type: 'FIRST_CONTACT_24H',
        target_hours: 12,
        compliance_rate: 0.98,
        total_checks: 80,
        breach_count: 2,
        last_breach_date: '2025-12-16',
      },
      {
        id: 50,
        dca_id: 'DCA-ZENITH-50',
        sla_type: 'FIRST_CONTACT_24H',
        target_hours: 48,
        compliance_rate: 0.86,
        total_checks: 480,
        breach_count: 67,
        last_breach_date: '2026-01-01',
      },
    ]);
    console.log('DCA data seeded successfully.');
  } catch (error) {
    console.error('Error seeding DCA data:', error);
  }
};

dcaseed();
